### ISSUE TITLE
Add authentication to MQTT

### ISSUE THREAD

**Issue by Jeltel** [johanmeijer/grott#1]
I got another sniffer running to locally read out my ShineWifi stick. But we ran into problems with the energy message. And you seems to have solved it :) So I would like to test it.

But I have authentication on my MQTT server. I can probably do a test and disable the authentication. But I'm not comfortable with leaving it that way. 
Can you add MQTT-authentication to your Python script?

**Comment by johanmeijer** [comment]
At this moment do not have authentication in MQTT enabled because I only use it in my own (home) network. 

I do think it is an added value to make it possible to enable authentication (via a parameter) and like to experiment with this. Do you use userid/password authentication or another security mechanism?

**Comment by Jeltel** [comment]
I use the mosquito home assistant add on: https://github.com/home-assistant/hassio-addons/blob/master/mosquitto/README.md

With the optional logins configuration set to only one account.
I suspect mosquito will have a lot of documentation around Mqtt authentication. Don't think it's to complicated.

**Comment by johanmeijer** [comment]
I added an option to specify MQTT autentication. 
You can now specify in the MQTT section of the INI file: 

auth = True
user = youruserid 
password = yourpassword 

Default: 
auth = False
user = grott
password = growatt2020

I hope you are able to test it. At this moment I do not have a secure MQTT available myself (will set this up later).

**Comment by Jeltel** [comment]
Works great btw :)
