### ISSUE TITLE
InfluxDB 2.0 "unable to parse" error

### ISSUE THREAD

**Issue by bkleef** [johanmeijer/grott#107]
In looks like the character `i` is appended after each JSON (integer) value? Like `epv1today=70i`. This happens in Grott version 2.6.1g.

```
	 - Growatt packet received:
		  <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.18.0.3', 41820), raddr=('47.91.67.66', 5279)>
	 - Growatt original Data:
		 \x00\x27\x00\x06\x02\x41\x51\x04\x09\x33\x2c\x4f\x23\x33\x43\x76\x47\x5f\x77
		 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
		 \x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74
		 \x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x75\x6a
		 \xcc\x78\x73\x72\x6f\x77\x61\x74\x74\x45\xe2\x6f\x77\x61\x74\x74\x47\x70\xfd
		 \x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
		 \x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x7c\xff\x69\x8c
		 \x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77
		 \x61\x74\x74\x4f\x8a\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
		 \x6f\x77\x61\x63\xd8\x83\x72\x6f\x77\x15\x74\x74\x4b\x71\x6f\x77\x6d\x07\x74
		 \x47\x72\x2b\x77\x61\x72\x6a\x47\x72\x6f\x44\x61\x74\x72\x12\x72\x6f\x77\x61
		 \x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f
		 \x77\x61\x74\x74\x30\x72\x6f\x7b\x12\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
		 \x72\x18\x77\x61\x74\x74\xb8\x88\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74
		 \x83\x47\x85\x6f\x77\x61\x74\x74\xb9\x70\x04\x77\x61\x3a\x54\x47\x72\x6f\x77
		 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x3f\x72
		 \x6f\x77\x61\x74\x74\x47\x4e\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74
		 \x47\x72\x6f\x77\x61\x0c\x78\x72\x7e\xde\x77\x61\x74\x74\x47\x72\x6f\x77\x61
		 \x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x7e\x1b
		 \x77\x61\x74\x0c\x47\x72\x63\x03\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
		 \x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74
		 \x74\x47\x72\x6f\x77\x61\x53\x64\x47\x72\x61\x67\x61\x74\x74\x47\x72\x6f\x77
		 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
		 \x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74
		 \x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61
		 \x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f
		 \x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
		 \x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74
		 \x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77
		 \x61\x75\x74\x46\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x44\x74\x77\x73
		 \x07\x60\x11\x53\x64\x47\x7b\x6f\x77\x61\x74\x74\x47\xbe\xa6
	 - Grott automatic protocol detection
	 - Grott data record length 585
	 - layout   :  T065104X
	 - no matching record layout found, try generic
	 - Record layout used :  T06NNNNX
	 - Growatt data decrypted V2
	 - Grott Growatt data decrypted
	 - Growatt plain data:
		 00270006024151044e41433842473731353000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000020bb8
		 0c340000000000000290000000000000029200000000000000000000000000000000000000000
		 000000000000000000000000000138808f8000000000000000000000000000000000000000000
		 0008f8000000000000000000000000000000000017acc40000007400000c0300000c730000004
		 40000061e00000033000006550000000000000000000000000000000000000000000000000000
		 007700000c7300000000000000000000007700000000fffa0000000000000000000000f700f70
		 000000000fe026b00004e20000000000000000000000000000000000000000000780000000000
		 00003c0000000000000000000000000000000000780c350cb1000000000000000000000000000
		 00000000000000000000000000c740000007800000c7400000000000000000000000000000000
		 0000000000000000000000000000000000000000271000000e100000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000010001000000000000000000000030003001681770271000090
		 00000000000ccc9
	 - Growatt new layout processing
		 - decrypt       :  True
		 - offset        :  6
		 - record layout :  T06NNNNX

	 - Grott data record date/time processing started
	 - no or no valid time/date found, grott server time will be used (buffer records not sent!)
	 - Grott values retrieved:
		 -  pvserial             :
		 -  recortype1           :  3000
		 -  recortype2           :  3124
		 -  pvstatus             :  0
		 -  pvpowerin            :  0.0
		 -  pv1voltage           :  65.6
		 -  pv1current           :  0.0
		 -  pv1watt              :  0.0
		 -  pv2voltage           :  65.8
		 -  pv2current           :  0.0
		 -  pv2watt              :  0.0
		 -  pvpowerout           :  0.0
		 -  pvfrequentie         :  50.0
		 -  pvgridvoltage        :  229.6
		 -  pvgridcurrent        :  0.0
		 -  pvgridpower          :  0.0
		 -  pvgridvoltage2       :  0.0
		 -  pvgridcurrent2       :  0.0
		 -  pvgridpower2         :  0.0
		 -  pvgridvoltage3       :  0.0
		 -  pvgridcurrent3       :  0.0
		 -  pvgridpower3         :  0.0
		 -  totworktime          :  215.5
		 -  pvenergytoday        :  11.6
		 -  pvenergytotal        :  307.5
		 -  epvtotal             :  318.7
		 -  epv1today            :  6.8
		 -  epv1total            :  156.6
		 -  epv2today            :  5.1
		 -  epv2total            :  162.1
		 -  pvtemperature        :  24.7
		 -  pvipmtemperature     :  25.4
	 - MQTT jsonmsg:
			 {"device": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
			 "time": "2022-03-15T22:34:29", "buffered": "no", "values": {"recortype1":
			 3000, "recortype2": 3124, "pvstatus": 0, "pvpowerin": 0, "pv1voltage": 656,
			 "pv1current": 0, "pv1watt": 0, "pv2voltage": 658, "pv2current": 0,
			 "pv2watt": 0, "pvpowerout": 0, "pvfrequentie": 5000, "pvgridvoltage": 2296,
			 "pvgridcurrent": 0, "pvgridpower": 0, "pvgridvoltage2": 0, "pvgridcurrent2":
			 0, "pvgridpower2": 0, "pvgridvoltage3": 0, "pvgridcurrent3": 0,
			 "pvgridpower3": 0, "totworktime": 1551556, "pvenergytoday": 116,
			 "pvenergytotal": 3075, "epvtotal": 3187, "epv1today": 68, "epv1total": 1566,
			 "epv2today": 51, "epv2total": 1621, "pvtemperature": 247,
			 "pvipmtemperature": 254}}
	 - No MQTT message sent, MQTT disabled
	 - Grott send data to PVOutput systemid:  89381 for inverter:
		 -  {'X-Pvoutput-Apikey': '**secret**', 'X-Pvoutput-SystemId': '89381'}
		 -  {'d': '20220315', 't': '22:34', 'v1': 11600, 'v2': 0.0, 'v6': 229.6}
	 - Grott PVOutput response:
		 -  OK 200: Added Status
	 - Grott InfluxDB publihing started
	 - Timezone local specified default timezone used
	 - Grott original time :  2022-03-15T22:34:29 adjusted UTC time for influx :  2022-03-15T21:34:29
	 - Grott influxdb jsonmsg:
			 [{'measurement': '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'time':
			 '2022-03-15T21:34:29', 'fields': {'pvserial':
			 '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'recortype1': 3000,
			 'recortype2': 3124, 'pvstatus': 0, 'pvpowerin': 0, 'pv1voltage': 656,
			 'pv1current': 0, 'pv1watt': 0, 'pv2voltage': 658, 'pv2current': 0,
			 'pv2watt': 0, 'pvpowerout': 0, 'pvfrequentie': 5000, 'pvgridvoltage': 2296,
			 'pvgridcurrent': 0, 'pvgridpower': 0, 'pvgridvoltage2': 0, 'pvgridcurrent2':
			 0, 'pvgridpower2': 0, 'pvgridvoltage3': 0, 'pvgridcurrent3': 0,
			 'pvgridpower3': 0, 'totworktime': 1551556, 'pvenergytoday': 116,
			 'pvenergytotal': 3075, 'epvtotal': 3187, 'epv1today': 68, 'epv1total': 1566,
			 'epv2today': 51, 'epv2total': 1621, 'pvtemperature': 247,
			 'pvipmtemperature': 254}}]
	 - Grott write to influxdb v2
	 - Grott InfluxDB error
(400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.1.1', 'X-Platform-Error-Code': 'invalid', 'Date': 'Tue, 15 Mar 2022 21:34:30 GMT', 'Content-Length': '670'})
HTTP response body: {"code":"invalid","message":"unable to parse 'epv1today=68i,epv1total=1566i,epv2today=51i,epv2total=1621i,epvtotal=3187i,pv1current=0i,pv1voltage=656i,pv1watt=0i,pv2current=0i,pv2voltage=658i,pv2watt=0i,pvenergytoday=116i,pvenergytotal=3075i,pvfrequentie=5000i,pvgridcurrent=0i,pvgridcurrent2=0i,pvgridcurrent3=0i,pvgridpower=0i,pvgridpower2=0i,pvgridpower3=0i,pvgridvoltage=2296i,pvgridvoltage2=0i,pvgridvoltage3=0i,pvipmtemperature=254i,pvpowerin=0i,pvpowerout=0i,pvserial=\"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\",pvstatus=0i,pvtemperature=247i,recortype1=3000i,recortype2=3124i,totworktime=1551556i 1647380069000000000': invalid field format"}
```

**Comment by johanmeijer** [comment]
OK. Interesting. I will look at that. I do not have that problem. 

Do you use the docker or native python version? You might have to update the python influxDBClient library. This one is influxdb version depended.

**Comment by bkleef** [comment]
@johanmeijer looks like this bug occurs when `pvserial` has no value: `-  pvserial             :`

[Here](https://www.diffchecker.com/VUhkEYJf) a message that works (left) and a few minutes later a message (right) where `pvserial` has no value and the error occurs.

Remarkably, the keys `measurement` and `pvserial` have the value `\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00` in the _Grott influxdb jsonmsg_ message if `pvserial` has no value.

**Comment by johanmeijer** [comment]
This seems very strange your record does not contain the inverter serial number. That is something I have not seen before. How does your configuration looks like? Which inverter type and datalogger do you use?

For Influxdb the pvserial is used for measurement identification. I do understand this can cause same errors.

**Comment by bkleef** [comment]
Configuration is still the same as [previously shared](https://github.com/johanmeijer/grott/issues/107#issuecomment-1069271601).

Inverter type: Growatt hybrid inverter MIN 6000TL-XH
Datalogger: Growatt Shinelink

[Here](https://drive.google.com/file/d/1_LbaBbMnk6sBj_u-OLsG-RKkVRbcP6on/view?usp=sharing) are more logs. Of the 245 times that `- pvserial` appears here, 150 have a value. In 37% of the cases, `pvserial` has no value.

**Comment by johanmeijer** [comment]
Sorry I read over that on my phone. But I am at the PC again ;). Nice inverter do you also have a battery connected? 

Did you have try to update the firmware of the shinelink. Maybe this is really a bug? Or maybe a total reset might help. 

If I look at your log (first look) I see also a lot of T065103X recorded. The "03" records are called "announce" records and announces the record to the growatt server. This is normally only than after a restart of Grott, a start of the inverter in the morning of after connection loss. And is only send once, not that often as in your log. This might point out to a bad connection with the growatt server (or maybe the RF connection between inverter and shinelink?). 

If we want to analyse the full protocol then we need to specify gminrecl = 1 this will show all trafic. This will generate even more log records. But we see then if the growatt server is acking the "03" records. The ack of this record is the start of a normal communication sequence. 

It is a strange error. I have not seen it before. I am also interested why you do not have a time in the data (04) record but I have seen that before with a shinelink. 

This is a "special" problem. I hope we can solve this. Of course we can insert an inverter id (specified ginverterid = ) if there is none detected. This will be a small change in Grott. But it feels like a dirty fix to solve growatt bugs. 

Are you willing to test this without the growatt server (using de beta Grottserver see discussions #98)? We can make a docker container for that also. 

I will also analyse the log more if I can see other strange things. If you want we can also communicatie in an other way (Mail, Chat, Zoom/Teams), this might be a difficult proces.

**Comment by johanmeijer** [comment]
@bkleef maybe this error is the same as mentioned in #104 ?

**Comment by johanmeijer** [comment]
I really think this is a connection error (between RF module and shinelink) or a firmware error in shinelink or RF module. 

The bulk "03" announce records do not contain an inverter ID either and will not be accepted by the growatt server. That is why there a lot of this records in your log. The shinelink will resend a new "03"  until it is accepted. 
In your file a count approximately 5500 "03" records (daily I have 2 or 3) and as you said only 245 "04" records (of which only 150 have the right information). 
Now I can understand growatt has communication problems if all Shinelink modules are doing this. 

Is there a possibility the RF communication is disturbed by some other signal or is the distance between inverter/shinelan and to big? Although I suppose that not only the PVserial should contain strange data.

**Comment by johanmeijer** [comment]
@bkleef see reaction on #104. Maybe you can perform a firmware upgrade?

**Comment by bkleef** [comment]
Thank you very much for your investigation. Quick reply, firmware version is 7.0.0.1 (hardware version is V1.0). Do you think this is the latest version?

**Comment by johanmeijer** [comment]
I really do not know (if have a shinewifi). You can see this at the datalogger pages at the growatt server website. 

![image](https://user-images.githubusercontent.com/16508298/159365161-6b8bf4a0-0ad3-424a-bbf0-a3a055f514fa.png)

**Comment by johanmeijer** [comment]
@bkleef  Have you already try to update the Firmware and did this show any improvements

**Comment by bkleef** [comment]
@johanmeijer I have contacted Growatt support. Today they have tried 3 times to update the box firmware without success. They will look into it internally.
The RF stick firmware is up to date.

The Shinelan-X is now also on the same floor and placed 2 meters away from the inverter. This makes no difference.
I'm thinking of buying the Growatt ShineWifi-X, maybe this will solve everything?

I also set `gminrecl=1` and `ginverterid=AHJ0BJ801H`. Log files can be downloaded [here](https://drive.google.com/file/d/1lW9fDLVSeoWxaHNlNU8MKKzo0iCc8Gl4/view?usp=sharing).

**Comment by johanmeijer** [comment]
It is really strange. Seems a hardware/ firmware error to me. To be honest I expected the RF stick would give the problem (because that is interfacing with the inverter and retrieves the Inverterid). But if this one is up to date then the change will be low I think. 

Just to be sure. What is your data transfer interval. I can not determine this from your log is seems to be very irregular. Maybe if you set this interval to low the datalogger can not keep up with this?

Using an other datalogger (shiniwifi) might solve the problem indeed (if is not inverter related).

Do you want me to implement a bypass (insert inverterid when this is not the datarecord)? I will also commit your pull request soon.

**Comment by johanmeijer** [comment]
I am curious if it will be solved.

Op do 9 jun. 2022 14:02 schreef Bart van Kleef ***@***.***>:

**Comment by rany2** [comment]
@johanmeijer What's the issue? I'm personally been using InfluxDB v2 for a few weeks without any issues.

**Comment by johanmeijer** [comment]
A lot of reconnects with the growatt server (losing connection and reinit again)
