### ISSUE TITLE
influxdb2 only recording values for 1 datalogger

### ISSUE THREAD

**Issue by ronosan** [johanmeijer/grott#110]
Hi,

I installed grott v2.6.1g and influxdb2 and got it working properly for 1 datalogger (i can see data in influxdb). However, my 2nd datalogger isn't showing up in influxdb despite a measurement has been created automatically by grott. This data logger is sending messages correctly to grott (running in proxy mode, same instance used by the working datalogger) and i can see the data is routed to Growatt servers correctly and displays in the Growatt phone app. Grott logs also show an influxdb json was created correctly for the troublesome datalogger, successfully sent to influxdb, but mysteriously missing with no data in influxdb?

Sample grott output for datalogger missing influxdb data:
`	 - Growatt packet received:
		  <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.123', 5279), raddr=('192.168.2.102', 51575)>
	 - Data less then minimum record length, data not processed

	 - Growatt packet received:
		  <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.123', 61004), raddr=('47.91.67.66', 5279)>
	 - Growatt original Data:
		 \x01\xbe\x00\x06\x02\x41\x01\x04\x1f\x35\x2b\x47\x58\x46\x43\x77\x43\x5e\x77
		 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
		 \x37\x23\x25\x46\x4d\x74\x47\x5e\x42\x51\x74\x74\x47\x72\x6f\x77\x61\x74\x74
		 \x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x77\x77\x64\x56\x75\x73\x75\x6a
		 \xcc\x78\x73\x72\x6e\x77\x61\x3f\xb8\x49\x11\x6f\x6b\x61\x74\x5e\xb7\x79\x69
		 \x77\x7a\x74\x74\x67\xae\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
		 \x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x0d\x35\x7c\xf1\x68\x0d
		 \x74\x17\x72\x6f\x3d\xec\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77
		 \x61\x74\x74\x4e\x0b\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
		 \x25\x30\x65\xd5\x82\xde\x72\x6f\x77\xe5\x74\x77\x54\x2c\x6f\x74\x7e\x99\x74
		 \x47\x72\x22\x77\x60\xb2\xdc\x47\x72\x6f\x4e\x61\x75\x2d\x02\x72\x6f\x77\x61
		 \x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f
		 \x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
		 \x72\x6f\x77\x61\x74\x74\x40\x55\x6f\x69\x61\x74\x74\x47\x66\x0e\x77\x61\x75
		 \x2f\x47\x72\x6f\x77\x61\x74\x75\xdf\x7d\xf7\x77\x61\x3a\x54\x47\x54\x6f\x77
		 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
		 \x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74
		 \x47\x72\x6f\x77\x61\x74\x78\x72\x7e\xde\x77\x61\x74\x74\x47\x72\x6f\x77\x61
		 \x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f
		 \x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
		 \x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74
		 \x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77
		 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
		 \x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74
		 \x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61
		 \x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f
		 \x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
		 \x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74
		 \x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77
		 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
		 \x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\xb4\x69
	 - Grott automatic protocol detection
	 - Grott data record length 585
	 - layout   :  T060104X
	 - no matching record layout found, try generic
	 - Record layout used :  T06NNNNX
	 - Growatt data decrypted V2
	 - Grott Growatt data decrypted
	 - Growatt plain data:
		 01be0006024101045847443039323730313100000000000000000000000000000000000000005
		 8544432393335313530000000000000000000000000000000000000000016031011071c020bb8
		 0c34000100004bcc0e63001c00002af00b06001b000020dc00000000000000000000000000000
		 000000000000000000000004a4713860979005000004a8d000000000000000000000000000000
		 00097900000000000000000000000000004a4704a1f699000000840003135e00031fed0000004
		 d0001c6a800000039000159450000000000000000000000000000000000000000000000000000
		 000000000000000000000000000000000000000000000727001e0000000014610000015b00000
		 000000001980f9800004e20002600000000000000000000000000000000000000000000000000
		 0000000000000000000000000000000000000000000c350cb1000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000c606
	 - Growatt new layout processing
		 - decrypt       :  True
		 - offset        :  6
		 - record layout :  T06NNNNX

	 - Grott data record date/time processing started
	 - date-time:  2022-03-16T17:07:28
	 - Grott values retrieved:
		 -  pvserial             :  XTD2935150
		 -  recortype1           :  3000
		 -  recortype2           :  3124
		 -  pvstatus             :  1
		 -  pvpowerin            :  1940.4
		 -  pv1voltage           :  368.3
		 -  pv1current           :  2.8
		 -  pv1watt              :  1099.2
		 -  pv2voltage           :  282.2
		 -  pv2current           :  2.7
		 -  pv2watt              :  841.2
		 -  pvpowerout           :  1901.5
		 -  pvfrequentie         :  50.0
		 -  pvgridvoltage        :  242.5
		 -  pvgridcurrent        :  8.0
		 -  pvgridpower          :  1908.5
		 -  pvgridvoltage2       :  0.0
		 -  pvgridcurrent2       :  0.0
		 -  pvgridpower2         :  0.0
		 -  pvgridvoltage3       :  0.0
		 -  pvgridcurrent3       :  0.0
		 -  pvgridpower3         :  0.0
		 -  totworktime          :  10794.9
		 -  pvenergytoday        :  13.2
		 -  pvenergytotal        :  20156.6
		 -  epvtotal             :  20478.1
		 -  epv1today            :  7.7
		 -  epv1total            :  11639.2
		 -  epv2today            :  5.7
		 -  epv2total            :  8838.9
		 -  pvtemperature        :  34.7
		 -  pvipmtemperature     :  40.8
	 - MQTT jsonmsg: 
			 {"device": "XTD2935150", "time": "2022-03-16T17:07:28", "buffered": "no",
			 "values": {"recortype1": 3000, "recortype2": 3124, "pvstatus": 1,
			 "pvpowerin": 19404, "pv1voltage": 3683, "pv1current": 28, "pv1watt": 10992,
			 "pv2voltage": 2822, "pv2current": 27, "pv2watt": 8412, "pvpowerout": 19015,
			 "pvfrequentie": 4998, "pvgridvoltage": 2425, "pvgridcurrent": 80,
			 "pvgridpower": 19085, "pvgridvoltage2": 0, "pvgridcurrent2": 0,
			 "pvgridpower2": 0, "pvgridvoltage3": 0, "pvgridcurrent3": 0, "pvgridpower3":
			 0, "totworktime": 77723289, "pvenergytoday": 132, "pvenergytotal": 201566,
			 "epvtotal": 204781, "epv1today": 77, "epv1total": 116392, "epv2today": 57,
			 "epv2total": 88389, "pvtemperature": 347, "pvipmtemperature": 408}}
	 - MQTT message message sent
	 - Grott Send data to PVOutput disabled 
	 - Grott InfluxDB publihing started
	 - Timezone local specified default timezone used
	 - Grott original time :  2022-03-16T17:07:28 adjusted UTC time for influx :  2022-03-16T07:07:28
	 - Grott influxdb jsonmsg: 
			 [{'measurement': 'XTD2935150', 'time': '2022-03-16T07:07:28', 'fields':
			 {'pvserial': 'XTD2935150', 'recortype1': 3000, 'recortype2': 3124,
			 'pvstatus': 1, 'pvpowerin': 19404, 'pv1voltage': 3683, 'pv1current': 28,
			 'pv1watt': 10992, 'pv2voltage': 2822, 'pv2current': 27, 'pv2watt': 8412,
			 'pvpowerout': 19015, 'pvfrequentie': 4998, 'pvgridvoltage': 2425,
			 'pvgridcurrent': 80, 'pvgridpower': 19085, 'pvgridvoltage2': 0,
			 'pvgridcurrent2': 0, 'pvgridpower2': 0, 'pvgridvoltage3': 0,
			 'pvgridcurrent3': 0, 'pvgridpower3': 0, 'totworktime': 77723289,
			 'pvenergytoday': 132, 'pvenergytotal': 201566, 'epvtotal': 204781,
			 'epv1today': 77, 'epv1total': 116392, 'epv2today': 57, 'epv2total': 88389,
			 'pvtemperature': 347, 'pvipmtemperature': 408}}]
	 - Grott write to influxdb v2
	 - Grott extension processing disabled 

`

Sample output for working datalogger showing up in influxdb:
`	 - Growatt packet received:
		  <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.123', 5279), raddr=('192.168.2.101', 14158)>
	 - Data less then minimum record length, data not processed

	 - Growatt packet received:
		  <socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.123', 61005), raddr=('47.91.67.66', 5279)>
	 - Growatt original Data:
		 \x01\xbf\x00\x06\x02\x41\x01\x04\x1f\x35\x2b\x43\x23\x44\x47\x76\x2b\x5c\x77
		 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
		 \x27\x3a\x26\x40\x36\x77\x41\x5c\x43\x58\x74\x74\x47\x72\x6f\x77\x61\x74\x74
		 \x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x77\x77\x64\x56\x7d\x6a\x75\x6a
		 \xcc\x78\x73\x72\x6e\x77\x61\x6f\x12\x57\x38\x6f\x70\x61\x74\x7a\xd8\x74\xe6
		 \x77\x70\x74\x74\x4b\xb5\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
		 \x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x5d\xa8\x7c\xf2\x68\x0c
		 \x74\x5a\x72\x6f\x6d\x9d\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77
		 \x61\x74\x74\x4e\x0a\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
		 \x6f\x77\x61\xfc\x29\x3c\x72\x6f\x77\xe4\x74\x74\x1e\x74\x6f\x77\x3b\xa8\x74
		 \x47\x72\x32\x77\x61\x34\x38\x47\x72\x6f\x5e\x61\x74\x6e\xd7\x72\x6f\x77\x61
		 \x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f
		 \x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
		 \x72\x6f\x77\x61\x74\x74\x48\x03\x6f\x4b\x61\x74\x74\x47\x72\x0f\x77\x61\x75
		 \x21\x47\x72\x6f\x77\x61\x74\x75\xd3\x63\xeb\x77\x61\x3a\x54\x47\x7f\x6f\x77
		 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
		 \x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74
		 \x47\x72\x6f\x77\x61\x74\x78\x72\x7e\xde\x77\x61\x74\x74\x47\x72\x6f\x77\x61
		 \x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f
		 \x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
		 \x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74
		 \x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77
		 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
		 \x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74
		 \x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61
		 \x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f
		 \x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
		 \x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74
		 \x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77
		 \x61\xa4\x74\x21\x72\x6f\x67\xe1\x65\x0e\x41\xf9\x6f\x77\x60\x57\x74\x47\x72
		 \x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x31\xa7
	 - Grott automatic protocol detection
	 - Grott data record length 585
	 - layout   :  T060104X
	 - no matching record layout found, try generic
	 - Record layout used :  T06NNNNX
	 - Growatt data decrypted V2
	 - Grott Growatt data decrypted
	 - Growatt plain data:
		 01bf0006024101045847443442303331593300000000000000000000000000000000000000004
		 84d47344230333334390000000000000000000000000000000000000000160310110f05020bb8
		 0c34000100001b66104a000700000e9f0689001100000cc700000000000000000000000000000
		 000000000000000000000001ada13850978001d00001afc000000000000000000000000000000
		 0009780000000000000000000000000000000000885d7b000000850000590600005adc0000005
		 d0000404c0000002900001a900000000000000000000000000000000000000000000000000000
		 000000000000000000000000000000000000000000000f71003c0000000000600000015500000
		 00000000194118400004e20000d00000000000000000000000000000000000000000000000000
		 0000000000000000000000000000000000000000000c350cb1000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000d0006600001080117a068b00000123000000000000000000000
		 0000000000043c8
	 - Growatt new layout processing
		 - decrypt       :  True
		 - offset        :  6
		 - record layout :  T06NNNNX

	 - Grott data record date/time processing started
	 - date-time:  2022-03-16T17:15:05
	 - Grott values retrieved:
		 -  pvserial             :  HMG4B03349
		 -  recortype1           :  3000
		 -  recortype2           :  3124
		 -  pvstatus             :  1
		 -  pvpowerin            :  701.4
		 -  pv1voltage           :  417.0
		 -  pv1current           :  0.7
		 -  pv1watt              :  374.3
		 -  pv2voltage           :  167.3
		 -  pv2current           :  1.7
		 -  pv2watt              :  327.1
		 -  pvpowerout           :  687.4
		 -  pvfrequentie         :  50.0
		 -  pvgridvoltage        :  242.4
		 -  pvgridcurrent        :  2.9
		 -  pvgridpower          :  690.8
		 -  pvgridvoltage2       :  0.0
		 -  pvgridcurrent2       :  0.0
		 -  pvgridpower2         :  0.0
		 -  pvgridvoltage3       :  0.0
		 -  pvgridcurrent3       :  0.0
		 -  pvgridpower3         :  0.0
		 -  totworktime          :  1241.2
		 -  pvenergytoday        :  13.3
		 -  pvenergytotal        :  2279.0
		 -  epvtotal             :  2326.0
		 -  epv1today            :  9.3
		 -  epv1total            :  1646.0
		 -  epv2today            :  4.1
		 -  epv2total            :  680.0
		 -  pvtemperature        :  34.1
		 -  pvipmtemperature     :  40.4
	 - MQTT jsonmsg: 
			 {"device": "HMG4B03349", "time": "2022-03-16T17:15:05", "buffered": "no",
			 "values": {"recortype1": 3000, "recortype2": 3124, "pvstatus": 1,
			 "pvpowerin": 7014, "pv1voltage": 4170, "pv1current": 7, "pv1watt": 3743,
			 "pv2voltage": 1673, "pv2current": 17, "pv2watt": 3271, "pvpowerout": 6874,
			 "pvfrequentie": 4997, "pvgridvoltage": 2424, "pvgridcurrent": 29,
			 "pvgridpower": 6908, "pvgridvoltage2": 0, "pvgridcurrent2": 0,
			 "pvgridpower2": 0, "pvgridvoltage3": 0, "pvgridcurrent3": 0, "pvgridpower3":
			 0, "totworktime": 8936827, "pvenergytoday": 133, "pvenergytotal": 22790,
			 "epvtotal": 23260, "epv1today": 93, "epv1total": 16460, "epv2today": 41,
			 "epv2total": 6800, "pvtemperature": 341, "pvipmtemperature": 404}}
	 - MQTT message message sent
	 - Grott Send data to PVOutput disabled 
	 - Grott InfluxDB publihing started
	 - Timezone local specified default timezone used
	 - Grott original time :  2022-03-16T17:15:05 adjusted UTC time for influx :  2022-03-16T07:15:05
	 - Grott influxdb jsonmsg: 
			 [{'measurement': 'HMG4B03349', 'time': '2022-03-16T07:15:05', 'fields':
			 {'pvserial': 'HMG4B03349', 'recortype1': 3000, 'recortype2': 3124,
			 'pvstatus': 1, 'pvpowerin': 7014, 'pv1voltage': 4170, 'pv1current': 7,
			 'pv1watt': 3743, 'pv2voltage': 1673, 'pv2current': 17, 'pv2watt': 3271,
			 'pvpowerout': 6874, 'pvfrequentie': 4997, 'pvgridvoltage': 2424,
			 'pvgridcurrent': 29, 'pvgridpower': 6908, 'pvgridvoltage2': 0,
			 'pvgridcurrent2': 0, 'pvgridpower2': 0, 'pvgridvoltage3': 0,
			 'pvgridcurrent3': 0, 'pvgridpower3': 0, 'totworktime': 8936827,
			 'pvenergytoday': 133, 'pvenergytotal': 22790, 'epvtotal': 23260,
			 'epv1today': 93, 'epv1total': 16460, 'epv2today': 41, 'epv2total': 6800,
			 'pvtemperature': 341, 'pvipmtemperature': 404}}]
	 - Grott write to influxdb v2
	 - Grott extension processing disabled 
`
sample screenshot from influxdb:
![image](https://user-images.githubusercontent.com/101693651/158526551-5b340968-3660-4b01-8233-9cd9faf5ed77.png)

Any idea what's going on? I can't see any errors anywhere :/

**Comment by johanmeijer** [comment]
Hmm I do not see any any error either. What if you filter on only 1 measurement? Can you look in table or csv format if there are
measurements bor both?

**Comment by ronosan** [comment]
filtering on 1 measurement for the correct datalogger:
![image](https://user-images.githubusercontent.com/101693651/158598128-72f15526-6d21-42e4-9a64-38bc755edbfb.png)

filtering on 1 measurement for the 'missing data' datalogger:
![image](https://user-images.githubusercontent.com/101693651/158598416-c852871f-57d3-4eb2-8563-b3a48bb34815.png)

Upon closer inspection, those few data points for the 'missing data' datalogger, appears to coincide with me attempting to troubleshoot this problem by restarting grott/influxdb. I've tried the latest grott master branch, and branch 2.5.4 but to no success.

Has anyone else managed to successfully run grott + influxdb with more than 1 datalogger? At the moment i don't think it's hardware or network issue between my dataloggers to grott (because the correct data is still forwarded to growatt servers). Could it be some sort of compatibility with the API between grott and influxdb? 

BTW I'm running influxdb2-2.1.1

**Comment by johanmeijer** [comment]
This might be a network connection error but then I do not expect that the measurements in the growatt website or phone app would be right.

Do you see any errors in the grott log? Do you see all influxdb writes for both inverters in the grott log?

**Comment by ronosan** [comment]
I checked the growatt phone app and it has accurate data points at 5 minute intervals. I also see every single packet logged by grott as received from both dataloggers. The biggest mystery is why the datapoints for 1 logger feeds into influxdb correctly whilst the other vanishes. Influxdb spits out irrelevant info messages (mostly compaction/snapshot related) and no errors/fatal messages.

There are absolutely no errors at all in the grott log running in verbose mode.

InfluxDB and grott are running on the same PC.

**Comment by ronosan** [comment]
i think there's an inherent problem with influxdb. I spent the day setting up telegraf agent to tap into grott's mqtt stream dataset and plumb that into influxdb. Same problem with the metric for the 2nd datalogger is missing once delivered to influxdb. Extremely frustrating.

Upon further reading into influxdb, i'm coming to the conclusion that it's a terribly unreliable database as they have bigger problems since v1.8 where chunks of existing data can suddenly disappear due to corruption. I think i need to explore an alternative as a datastore...

**Comment by johanmeijer** [comment]
Ok. Have not problems with it until now. If you know Which database you want use (e.g. mysql, postgres,mongodb, Prometheus) we can try to build in support (create an extension) for that one as well.

I have to admit I primarily use influxdb 1.x because that was the standard for raspberry pi. I have influxdb 2.x running in a docker container for testing (support) purposes.
