### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by thomytp** [johanmeijer/grott#113]
Hello,
ich use Grott with docker and mosquito. from the Grott console, I can test the Port 1883 to the mosquito.
/app # nc 192.168.111.46 -v -z 1883
192.168.111.46 (192.168.111.46:1883) open
/app # 

the installation works for 5 days, now Grott does not publish the topic to the Mqtt broker.
In the last week, there was a update pull from mosquito.. this may be the reason?

**Comment by johanmeijer** [comment]
Do you see any mqtt messages in the grott log? 

Do you use mqtt security or are defaults changed in this area?

**Comment by thomytp** [comment]
i have thins informationen from the log: 

Grott proxy mode started
Hostname : 52c367eofd96
IP :  172.17.0.2 , port :  5279 

Grott Growatt logging monitor : 2.5.2

Grott Command line parameters processed:
	verbose:     	 True
	config file: 	 grott.ini
	output file: 	 <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
	nomqtt:      	 False
	inverterid:  	 automatic
	pvoutput:    	 False
	blockcmd:    	 False
	noipf:       	 False

Grott process configuration file

Grott process environmental variables

Grott override settings if set in commandline

Grott process json layout files

Grott layout records loaded
T02NNNN  : 
{'decrypt': {'value': 'False'}, 'pvserial': {'value': 36, 'length': 10, 'type': 'text', 'divide': 10}, 'date': {'value': 56, 'divide': 10}, 'pvstatus': {'value': 78, 'length': 2, 'type': 'num'}, 'pvpowerin': {'value': 82, 'length': 4, 'type': 'num', 'divide': 10}, 'pv1voltage': {'value': 90, 'length': 2, 'type': 'num', 'divide': 10}, 'pv1current': {'value': 94, 'length': 2, 'type': 'num', 'divide': 10}, 'pv1watt': {'value': 98, 'length': 4, 'type': 'num', 'divide': 10}, 'pv2voltage': {'value': 106, 'length': 2, 'type': 'num', 'divide': 10}, 'pv2current': {'value': 110, 'length': 2, 'type': 'num', 'divide': 10}, 'pv2watt': {'value': 114, 'length': 4, 'type': 'num', 'divide': 10}, 'pvpowerout': {'value': 122, 'length': 4, 'type': 'num', 'divide': 10}, 'pvfrequentie': {'value': 130, 'length': 2, 'type': 'num', 'divide': 100}, 'pvgridvoltage': {'value': 134, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridcurrent': {'value': 138, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridpower': {'value': 142, 'length': 4, 'type': 'num', 'divide': 10}, 'pvgridvoltage2': {'value': 150, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridcurrent2': {'value': 154, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridpower2': {'value': 158, 'length': 4, 'type': 'num', 'divide': 10}, 'pvgridvoltage3': {'value': 166, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridcurrent3': {'value': 170, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridpower3': {'value': 174, 'length': 4, 'type': 'num', 'divide': 10}, 'pvenergytoday': {'value': 182, 'length': 4, 'type': 'num', 'divide': 10}, 'pvenergytotal': {'value': 190, 'length': 4, 'type': 'num', 'divide': 10}, 'totworktime': {'value': 198, 'length': 4, 'type': 'num', 'divide': 7200}, 'pvtemperature': {'value': 206, 'length': 2, 'type': 'num', 'divide': 10}, 'pvipmtemperature': {'value': 242, 'length': 2, 'type': 'num', 'divide': 10}, 'epv1today': {'value': 278, 'length': 4, 'type': 'num', 'divide': 10}, 'epv1total': {'value': 286, 'length': 4, 'type': 'num', 'divide': 10}, 'epv2today': {'value': 294, 'length': 4, 'type': 'num', 'divide': 10}, 'epv2total': {'value': 302, 'length': 4, 'type': 'num', 'divide': 10}, 'epvtotal': {'value': 310, 'length': 4, 'type': 'num', 'divide': 10}}
T05NNNN  : 
{'decrypt': {'value': 'True'}, 'pvserial': {'value': 36, 'length': 10, 'type': 'text', 'divide': 10}, 'date': {'value': 56, 'divide': 10}, 'pvstatus': {'value': 78, 'length': 2, 'type': 'num'}, 'pvpowerin': {'value': 82, 'length': 4, 'type': 'num', 'divide': 10}, 'pv1voltage': {'value': 90, 'length': 2, 'type': 'num', 'divide': 10}, 'pv1current': {'value': 94, 'length': 2, 'type': 'num', 'divide': 10}, 'pv1watt': {'value': 98, 'length': 4, 'type': 'num', 'divide': 10}, 'pv2voltage': {'value': 106, 'length': 2, 'type': 'num', 'divide': 10}, 'pv2current': {'value': 110, 'length': 2, 'type': 'num', 'divide': 10}, 'pv2watt': {'value': 114, 'length': 4, 'type': 'num', 'divide': 10}, 'pvpowerout': {'value': 122, 'length': 4, 'type': 'num', 'divide': 10}, 'pvfrequentie': {'value': 130, 'length': 2, 'type': 'num', 'divide': 100}, 'pvgridvoltage': {'value': 134, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridcurrent': {'value': 138, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridpower': {'value': 142, 'length': 4, 'type': 'num', 'divide': 10}, 'pvgridvoltage2': {'value': 150, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridcurrent2': {'value': 154, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridpower2': {'value': 158, 'length': 4, 'type': 'num', 'divide': 10}, 'pvgridvoltage3': {'value': 166, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridcurrent3': {'value': 170, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridpower3': {'value': 174, 'length': 4, 'type': 'num', 'divide': 10}, 'pvenergytoday': {'value': 182, 'length': 4, 'type': 'num', 'divide': 10}, 'pvenergytotal': {'value': 190, 'length': 4, 'type': 'num', 'divide': 10}, 'totworktime': {'value': 198, 'length': 4, 'type': 'num', 'divide': 7200}, 'pvtemperature': {'value': 206, 'length': 2, 'type': 'num', 'divide': 10}, 'pvipmtemperature': {'value': 242, 'length': 2, 'type': 'num', 'divide': 10}, 'epv1today': {'value': 278, 'length': 4, 'type': 'num', 'divide': 10}, 'epv1total': {'value': 286, 'length': 4, 'type': 'num', 'divide': 10}, 'epv2today': {'value': 294, 'length': 4, 'type': 'num', 'divide': 10}, 'epv2total': {'value': 302, 'length': 4, 'type': 'num', 'divide': 10}, 'epvtotal': {'value': 310, 'length': 4, 'type': 'num', 'divide': 10}}
T06NNNN  : 
{'decrypt': {'value': 'True'}, 'pvserial': {'value': 76, 'length': 10, 'type': 'text', 'divide': 10}, 'date': {'value': 136, 'divide': 10}, 'pvstatus': {'value': 158, 'length': 2, 'type': 'num'}, 'pvpowerin': {'value': 162, 'length': 4, 'type': 'num', 'divide': 10}, 'pv1voltage': {'value': 170, 'length': 2, 'type': 'num', 'divide': 10}, 'pv1current': {'value': 174, 'length': 2, 'type': 'num', 'divide': 10}, 'pv1watt': {'value': 178, 'length': 4, 'type': 'num', 'divide': 10}, 'pv2voltage': {'value': 186, 'length': 2, 'type': 'num', 'divide': 10}, 'pv2current': {'value': 190, 'length': 2, 'type': 'num', 'divide': 10}, 'pv2watt': {'value': 194, 'length': 4, 'type': 'num', 'divide': 10}, 'pvpowerout': {'value': 202, 'length': 4, 'type': 'num', 'divide': 10}, 'pvfrequentie': {'value': 210, 'length': 2, 'type': 'num', 'divide': 100}, 'pvgridvoltage': {'value': 214, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridcurrent': {'value': 218, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridpower': {'value': 222, 'length': 4, 'type': 'num', 'divide': 10}, 'pvgridvoltage2': {'value': 230, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridcurrent2': {'value': 234, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridpower2': {'value': 238, 'length': 4, 'type': 'num', 'divide': 10}, 'pvgridvoltage3': {'value': 246, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridcurrent3': {'value': 250, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridpower3': {'value': 254, 'length': 4, 'type': 'num', 'divide': 10}, 'pvenergytoday': {'value': 262, 'length': 4, 'type': 'num', 'divide': 10}, 'pvenergytotal': {'value': 270, 'length': 4, 'type': 'num', 'divide': 10}, 'totworktime': {'value': 278, 'length': 4, 'type': 'num', 'divide': 7200}, 'pvtemperature': {'value': 286, 'length': 2, 'type': 'num', 'divide': 10}, 'pvipmtemperature': {'value': 322, 'length': 2, 'type': 'num', 'divide': 10}, 'epv1today': {'value': 358, 'length': 4, 'type': 'num', 'divide': 10}, 'epv1total': {'value': 366, 'length': 4, 'type': 'num', 'divide': 10}, 'epv2today': {'value': 374, 'length': 4, 'type': 'num', 'divide': 10}, 'epv2total': {'value': 382, 'length': 4, 'type': 'num', 'divide': 10}, 'epvtotal': {'value': 390, 'length': 4, 'type': 'num', 'divide': 10}}

T05NNNNX  : 
{'decrypt': {'value': 'True'}, 'pvserial': {'value': 36, 'length': 10, 'type': 'text', 'divide': 10}, 'date': {'value': 56, 'divide': 10}, 'pvstatus': {'value': 78, 'length': 2, 'type': 'num'}, 'pvpowerin': {'value': 82, 'length': 4, 'type': 'num', 'divide': 10}, 'pv1voltage': {'value': 90, 'length': 2, 'type': 'num', 'divide': 10}, 'pv1current': {'value': 94, 'length': 2, 'type': 'num', 'divide': 10}, 'pv1watt': {'value': 98, 'length': 4, 'type': 'num', 'divide': 10}, 'pv2voltage': {'value': 106, 'length': 2, 'type': 'num', 'divide': 10}, 'pv2current': {'value': 110, 'length': 2, 'type': 'num', 'divide': 10}, 'pv2watt': {'value': 114, 'length': 4, 'type': 'num', 'divide': 10}, 'pvpowerout': {'value': 170, 'length': 4, 'type': 'num', 'divide': 10}, 'pvfrequentie': {'value': 178, 'length': 2, 'type': 'num', 'divide': 100}, 'pvgridvoltage': {'value': 182, 'length': 2, 'type': 'num', 'divide': 10}, 'pvenergytoday': {'value': 274, 'length': 4, 'type': 'num', 'divide': 10}, 'pvenergytotal': {'value': 282, 'length': 4, 'type': 'num', 'divide': 10}, 'pvtemperature': {'value': 450, 'length': 2, 'type': 'num', 'divide': 10}, 'pvipmtemperature': {'value': 454, 'length': 2, 'type': 'num', 'divide': 10}}

T06NNNNX  : 
{'pvserial': {'value': 76, 'length': 10, 'type': 'text', 'divide': 10}, 'date': {'value': 136, 'divide': 10}, 'pvstatus': {'value': 158, 'length': 2, 'type': 'num'}, 'pvpowerin': {'value': 162, 'length': 4, 'type': 'num', 'divide': 10}, 'pv1voltage': {'value': 170, 'length': 2, 'type': 'num', 'divide': 10}, 'pv1current': {'value': 174, 'length': 2, 'type': 'num', 'divide': 10}, 'pv1watt': {'value': 178, 'length': 4, 'type': 'num', 'divide': 10}, 'pv2voltage': {'value': 186, 'length': 2, 'type': 'num', 'divide': 10}, 'pv2current': {'value': 190, 'length': 2, 'type': 'num', 'divide': 10}, 'pv2watt': {'value': 194, 'length': 4, 'type': 'num', 'divide': 10}, 'pvpowerout': {'value': 250, 'length': 4, 'type': 'num', 'divide': 10}, 'pvfrequentie': {'value': 258, 'length': 2, 'type': 'num', 'divide': 100}, 'pvgridvoltage': {'value': 262, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridcurrent': {'value': 266, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridpower': {'value': 270, 'length': 4, 'type': 'num', 'divide': 10}, 'pvgridvoltage2': {'value': 278, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridcurrent2': {'value': 282, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridpower2': {'value': 286, 'length': 4, 'type': 'num', 'divide': 10}, 'pvgridvoltage3': {'value': 294, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridcurrent3': {'value': 298, 'length': 2, 'type': 'num', 'divide': 10}, 'pvgridpower3': {'value': 302, 'length': 4, 'type': 'num', 'divide': 10}, 'totworktime': {'value': 346, 'length': 4, 'type': 'num', 'divide': 7200}, 'pvenergytoday': {'value': 354, 'length': 4, 'type': 'num', 'divide': 10}, 'pvenergytotal': {'value': 362, 'length': 4, 'type': 'num', 'divide': 10}, 'epvtotal': {'value': 370, 'length': 4, 'type': 'num', 'divide': 10}, 'epv1today': {'value': 378, 'length': 4, 'type': 'num', 'divide': 10}, 'epv1total': {'value': 386, 'length': 4, 'type': 'num', 'divide': 10}, 'epv2today': {'value': 394, 'length': 4, 'type': 'num', 'divide': 10}, 'epv2total': {'value': 402, 'length': 4, 'type': 'num', 'divide': 10}, 'pvtemperature': {'value': 530, 'length': 2, 'type': 'num', 'divide': 10}, 'pvipmtemperature': {'value': 534, 'length': 2, 'type': 'num', 'divide': 10}}

Grott external record whitelist 'recwl.txt' not found

Grott records whitelisted :  {'0116', '0150', '5150', '5116', '5019', '0104', '5003', '5016', '5050', '5119', '5104', '0103', '5004', '0119', '5103'}

Grott settings:


:
	version:     	 2.5.2
	verbose:     	 True
	trace:       	 False
	config file: 	 grott.ini
	minrecl:     	 100
	decrypt:     	 True
	compat:      	 False
	blockcmd:    	 True
	noipf:       	 False
	time:        	 auto
	sendbuf:     	 True
	timezone:    	 local
	valueoffset: 	 6
	offset:      	 6
	inverterid:  	 automatic
	mode:        	 proxy
	grottip      	 default
	grottport    	 5279
_MQTT:
	nomqtt       	 False
	mqttip:      	 192.168.111.46
	mqttport:    	 1883
	mqtttopic:   	 energy/growatt
	mqtttauth:   	 True
	mqttuser:    	 user
	mqttpsw:     	 **secret**
_Growatt server:
	growattip:   	 47.91.67.66
	growattport: 	 5279
_PVOutput:
	pvoutput:    	 False
	pvurl:       	 https://pvoutput.org/service/r2/addstatus.jsp
	pvapikey:    	 yourapikey
	pvinverters: 	 1
	pvsystemid:  	 systemid1
_Influxdb:
	influx:      	 False
	influx2:     	 False
	database:    	 grottdb
	ip:          	 localhost
	port:        	 8086
	user:        	 grott
	password:    	 **secret**
	organization:	 grottorg
	bucket:      	 grottdb
	token:       	 **secret**
_Extension:
	extension:   	 False
	extname:     	 grottext
	extvar:      	 {'none': 'none'}


Grott proxy mode started
Hostname : 52c367ecfd96
IP :  172.17.0.2 , port :  5279

**Comment by johanmeijer** [comment]
If this is the only thing within the log then there is no data sent from the Inverter to Grott.

Maybe the IP address of the server Grott is running on has changed? Or the inverter/datalogger setting for the destination IP has been changed.

**Comment by thomytp** [comment]
strange.. the config on the Growatt wifi stick are changed to the standard setting. I set the internal ip again, now I  become the Mqtt Message.

I think the data below the message T02NNNN  are Data from the Inverter?

Thanks for your quick response.. :-)
