### ISSUE TITLE
[WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by hopSilentSimon** [johanmeijer/grott#121]
When I start the program (Windows server) It works fine for a couple of moments; PVoutput and MQTT works fine.
But then the scripts hangs. When I do a ctrl-c the programs resumes OR I get the following error:

[WinError 10054] An existing connection was forcibly closed by the remote host

Those Growatt packet received, I get every second or so? And every minute or so a package with actual data which gets processed just fine.

```
         - Growatt packet received:
                  <socket.socket fd=580, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.150', 56195), raddr=('47.91.67.66', 5279)>
         - Growatt command block checking started
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=580, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.150', 56195), raddr=('47.91.67.66', 5279)>
         - Growatt command block checking started
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=580, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.150', 56195), raddr=('47.91.67.66', 5279)>
         - Growatt command block checking started
Traceback (most recent call last):
  File "C:\grott\grott.py", line 35, in <module>
    proxy.main(conf)
  File "C:\grottproxy.py", line 85, in main
    self.on_recv(conf)
  File "C:\grott\grottproxy.py", line 166, in on_recv
    self.channel[self.s].send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

```

**Comment by johanmeijer** [comment]
It looks like the connection with the Growatt server is beeing closed. 

Which grott version are you using? Do you run grott as a windows service or in (power) shell window? 

CRtl-C is a little bit fussy in windows. It pauzes the processing I believe. If I want to stop the program i have to do ctrl-fn-pause/break. 

Be aware that the standard inverter interval is 5 minutes. In between not a lot happens (only occasionally a ping).
