### ISSUE TITLE
AP mode web interface doesn't work in latest ShineWifi-S firmware 

### ISSUE THREAD

**Issue by rany2** [johanmeijer/grott#129]
After updating ShineWifi-S firmware to fix some issues  I noticed something important, the web interface in AP mode is no longer available. 

What are alternative methods to reconfigure the datalogger if the WiFi AP/server IP/etc changed?

ALSO if you have upgraded, confirm if you still have the web interface or not.

**Comment by rany2** [comment]
PS I'm aware I could use their applications to configure it but I'm wondering if there is a way that doesn't rely on Growatt's apps

**Comment by johanmeijer** [comment]
I only have the AP mode if I reset the datalogger. After configuring I am not able to contact the datalogger directly. 

I have not tested if this is not available any more after the firmware upgrade and do not have plans for that seeing your experiences. One golden rule do not fix things that are not broken ;)

**Comment by johanmeijer** [comment]
Oke. I am not sure how I did configure it the beginning. I think I connected to the Wifi of the ESP and go the the x.x.x.1 address from the browser but I am not sure. Is that what is not available anymore?

**Comment by rany2** [comment]
What's no longer available is configuring it from 192.168.10.100

**Comment by Benchamoneh** [comment]
I have an existing ShineWifi-S already configured and working on server.growatt.com. I would like to add Grott for HA integration but as is noted above the stick no longer responds to HTTP requests. My firmware version is 3.0.0.2.

Is it clear in this case how to add Grott? I notice on server.growatt.com I can specify an IP which I think I should just put in the IP of my local Grott server, but I am worried that if I enter the IP here and it isn't working correctly then I will no longer have access to the ShineWifi-S and no longer be able to control my inverter.

Has anyone had success using Grott with the ShineWifi-S logger?
![image](https://github.com/johanmeijer/grott/assets/840037/167a756a-a734-45ba-ae46-be96647ddb0b)

**Comment by rany2** [comment]
Hi, yes use that field to set it the grott server. It should work fine :)

**Comment by Benchamoneh** [comment]
My logger was set up by my inverter installers so I never configured it in AP mode as they did it for me. However I have I configured via the website like everyone else today with success, thanks for the support.

I have seen on YouTube that you can access the stick if you reset it and reconfigure, and that way seems to be the only way to increase the reporting interval from the default of 5 minutes, but I didn't feel brave enough to try that today

**Comment by johanmeijer** [comment]
you can also change the upgrade frequency via the Growatt website. You can set register 4 with a other value (please read it first to verify, it should be set to 5). 2 means every 2 minutes. 0.5 every half a minute. But that will be something that can not achieved with the Growatt server. It will not keep up with high update frequencies. You then might consider to move to grottserver (emulating the growatt server).
