### ISSUE TITLE
Is it possible to increase the interval?

### ISSUE THREAD

**Issue by skinkie** [johanmeijer/grott#140]
On the wiki I notice that you are able to change the interval for a WiFi stick. https://github.com/johanmeijer/grott/wiki/Rerouting-Growatt-Wifi-TCPIP-data-via-your-Grott-Server

As having the LAN variant, I don't see a user configurable option to increase the interval. Is there any option to do so?
![image](https://user-images.githubusercontent.com/502394/183282334-2b52576b-ec88-483c-9687-5bb884b3df6d.png)

**Comment by johanmeijer** [comment]
Yes that is possible see discussions #93. 

https://github.com/johanmeijer/grott/discussions/93

It can be done via the growatt website or if you use grottserver then it can be done using the API.

**Comment by skinkie** [comment]
@johanmeijer thanks!! Confirmed!

![image](https://user-images.githubusercontent.com/502394/183295157-e0284ca5-63c0-467c-98a4-b9d5bbab8004.png)

**Comment by johanmeijer** [comment]
You can also specify interval < 1 minutes (e.g. 0.5) but the Growatt server might have problems to keep up with this.
