### ISSUE TITLE
Lots off errors in log

### ISSUE THREAD

**Issue by RienduPre** [johanmeijer/grott#179]
Hi,

I added one of mine Solar inverters (Model MIC 2500TL-X)

The connection is made, but it looses connection again with lots of error in the logging (see below)

I'm using Grott server 2.6.1g

Any help is more than welcome.

`Grott proxy mode started
Hostname : grott-server
IP :  192.168.0.170 , port :  5279 

         - ('192.168.0.54', 30182) has connected

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 39966), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 39966), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 5279), raddr=('192.168.0.54', 30182)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 5279), raddr=('192.168.0.54', 30182)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 39966), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 39966), raddr=('47.91.67.66', 5279)>
         - Growatt original Data:
                 \x00\x07\x00\x06\x02\x41\x01\x03\x1f\x35\x2b\x42\x23\x33\x38\x71\x25\x2d\x77
                 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
                 \x2c\x3a\x26\x40\x36\x03\x45\x5f\x45\x26\x74\x74\x47\x72\x6f\x77\x61\x74\x74
                 \x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x77\x7e\x75\x4b\x40\x41\x75\x61
                 \x74\x74\x3b\x72\x6e\x77\x78\x74\x74\x47\x16\x6f\x77\x46\x64\x74\x47\x13\xc7
                 \x74\x89\x33\x3c\x76\x5c\x5f\x77\x3b\x35\x35\x06\x72\x64\x77\x60\x74\x74\x44
                 \x52\x6f\x4b\x61\x48\x67\xcf\x61\xe7\x77\x61\x37\x39\x00\x46\x2d\x33\x56\x44
                 \x46\x00\x72\x6f\x77\x61\x74\x75\x47\x16\x6f\x77\x61\x74\x54\x67\x52\x3f\x21
                 \x41\x3d\x1a\x31\x17\x1d\x03\x04\x06\x54\x67\x72\x6f\x63\x31\x76\x75\x40\x94
                 \x6f\x7d\x61\x75\x74\x4b\x72\x58\x77\x7b\x74\x72\x40\x42\x65\x22\x73\xfa\x60
                 \x59\x75\x5f\x7d\x34\x66\xfa\x53\x6c\x6f\x77\x61\x74\x74\x47\x72\x6f\x70\xc2
                 \x7d\x96\x55\xe1\x7c\xfa\x61\x46\x74\x75\x72\x5d\x77\x53\x74\x46\x47\x40\x6f
                 \x45\x61\x46\x74\x75\x72\x5d\x77\x61\x74\x74\x4e\x90\x6f\x77\x26\x3c\x35\x06
                 \x42\x5a\x42\x51\x54\x54\x76\x43\x6e\x46\x61\x74\x74\x47\x61\xf3\x77\x7b\x7d
                 \xc0\x4e\x90\x67\x33\x69\x62\x74\x53\x72\x6a\x7e\x0e\x7c\x88\x60\x62\x48\x67
                 \x46\x64\x53\x57\x55\x7f\x50\x71\x74\xe2\x47\x72\x6e\x93\x61\x8b\x3a\x67\x72
                 \x90\x39\x41\x74\x8b\x09\x52\x6f\x88\x2f\x54\x75\x47\x72\x6f\x78\x60\x74\x6d
                 \x47\x72\x6f\x77\x61\x74\x7f\xff\x7e\x5b\x77\x61\x37\x39\x00\x46\x2d\x33\x56
                 \x44\x46\x00\x42\x5f\x47\x51\x44\x44\x77\x42\x5f\x47\x51\x44\x44\x77\x42\x5f
                 \x47\x51\x44\x44\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
                 \x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74
                 \x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77
                 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
                 \x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74
                 \x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61
                 \x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f
                 \x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
                 \x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74
                 \x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77
                 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
                 \x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x6d\x35
         - Grott automatic protocol detection
         - Grott data record length 585
         - layout   :  T060103X
         - no matching record layout found, try generic
         - Record layout used :  T060103X
         - Growatt data decrypted V2
         - Grott Growatt data decrypted
         - Growatt plain data:
                 00070006024101035847443542474c36574200000000000000000000000000000000000000004
                 34d47344244373032470000000000000000000000000000000000000000160a010c322e020000
                 007c000100190000006400002710000061a803e84748312e30005a414141000b0001000003200
                 03c003c138813880000434d473442443730324700000000000100640000000020202050562049
                 6e766572746572202000001450020107e6000a0001000c0037001a000607300a55128e141e073
                 00a55128e141e000000000000000007a309e21293138d00320032003200320032003200320032
                 003200320000000009e20000474841413035353020203131013100000000139c001a09b409e20
                 844081600140005096f08fc2710271027102710271027100096000001e400ff4e2000ff4e2000
                 ff4e2000ff4e20010000000f0100190000000000000bb80c340000434d4734424437303247303
                 03030303030303030303030303030303030300000000000000000000000000000000000000000
                 00000000000000000000000000000000000000000000000000000000000000000000000000000
                 00000000000000000000000000000000000000000000000000000000000000000000000000000
                 00000000000000000000000000000000000000000000000000000000000000000000000000000
                 00000000000000000000000000000000000000000000000000000000000000000000000000000
                 00000000000000000000000000000000000000000000000000000000000000000000000000000
                 000000000001f5a
         - Grott data ack record or data record not defined no processing done

         - Growatt packet received:
                  <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 5279), raddr=('192.168.0.54', 30182)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 39966), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 39966), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 39966), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 39966), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 39966), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 5279), raddr=('192.168.0.54', 30182)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 39966), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 39966), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 39966), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 39966), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 39966), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 39966), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 39966), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.0.170', 39966), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed
`

**Comment by johanmeijer** [comment]
Data less then minimum record length, data not processed is not on error. This means that grott skips ti's record because it is not a data record to process.

I am not sure if and why you loose connection. It is not shown in this part of the log.

**Comment by RienduPre** [comment]
Hi Johan,

Thanks for the quick response.
The connection problem were caused due to a duplicate ip adres and if the other issues about the record length are 'normal' I will close this issue.

I have a question about connecting 2 Growatt inverters, but I will create a new issue for that.

Thanks,
Rien
