### ISSUE TITLE
Issue with Docker image

### ISSUE THREAD

**Issue by ageurtse** [johanmeijer/grott#188]
Is there some kind off isue with the docker image, i get a strange error that the image could not be downloaded

![image](https://user-images.githubusercontent.com/2020670/196024708-df761fb7-8322-4166-9e98-95d2c26927c1.png)

**Comment by ageurtse** [comment]
Found the problem, somehow it was also runing on the local file system, so the ports where already taken.

**Comment by johanmeijer** [comment]
Issue solved I think

**Comment by Freekers** [comment]
This issue can be closed I think. Image is available and works as far as I can see.
