### ISSUE TITLE
Making sense of Grott Values

### ISSUE THREAD

**Issue by farsonic** [johanmeijer/grott#217]
I'm trying to make sense of the values being presented by Grott (and exported using MQTT) compared to what I'm seeing from the Growatt site. 

![Screen Shot 2022-11-04 at 3 16 10 pm](https://user-images.githubusercontent.com/5546448/199895844-81a0f1e8-acd8-40df-adc3-aa5b31fcc34f.png)

How do I rationalise the values?

**Comment by johanmeijer** [comment]
Interesting. Are they from the same time?

**Comment by farsonic** [comment]
Yes, my recordings from grott seem to have a higher value that matches the growatt site then a smaller value that doesn’t make sense. 

4 Nov 2022 at 23:00 by ***@***.***:

**Comment by johanmeijer** [comment]
What type of inverter do you have?

**Comment by farsonic** [comment]
5000TL-X





8 Nov 2022 at 05:33 by ***@***.***:

**Comment by W1ll3mp13** [comment]
I'm having the same issue. It looks like the values from Grott are shuffled.
There is some delay of the data in below screenshots (The grott data was from this afternoon and the GroWatt data from just now), but I guess the output data of for example epv1today (4619.6) is the total energy and should be placed at the value of pvenergytotal.
The inverter I have is 4000 TL3-S.
Is there a way to get the correct values at the correct properties? As a work around I can also manipulate the sensors I'm using in Home assisant to get the correct values in Home assistant. 
![Screenshot 2022-11-07 224600](https://user-images.githubusercontent.com/63806483/200424688-3ba54bb4-f324-49d7-ba61-baa35ba8f6d8.png)
![Screenshot 2022-11-07 224735](https://user-images.githubusercontent.com/63806483/200424690-29a532bb-3dcc-481d-b3ad-6a20f85ce8f9.png)

**Comment by johanmeijer** [comment]
@W1ll3mp13 for the TL3-S you have to specify invtype = tl3 or ginvtype = "tl3" (docker).

**Comment by johanmeijer** [comment]
@farsonic you also have a energy monitor (SDm630)  II believe. Is it possible that you try to compare the energy monitor data with the inverter (solar) data?

**Comment by farsonic** [comment]
That’s possible, let me check today 

12 Nov 2022 at 01:46 by ***@***.***:

**Comment by W1ll3mp13** [comment]
> @W1ll3mp13 for the TL3-S you have to specify invtype = tl3 or ginvtype = "tl3" (docker).

Dankjewel Johan. Het werkt :-)

**Comment by johanmeijer** [comment]
Super, fijn dat het wekt!
