### ISSUE TITLE
Parsing of Boolean values should be case insensitive

### ISSUE THREAD

**Issue by benpeart** [johanmeijer/grott#24]
When specifying boolean environment variables or command line options, traditionally they are all lower case. When I attempted this, it didn't work and it took me a while to figure out I had to do mixed case.  Making them case insensitive would be more flexible and less error prone.

**Comment by johanmeijer** [comment]
The mixed case for boolean (first character uppercase) is a python naming convention. I do understand this can be confusing if you have to specify this in the parameters.

I will try to improve this in the next releases. Thanks.

**Comment by johanmeijer** [comment]
Versie 2.3.0 (now available in the beta branche) also allow lower-case boolean in .ini and environmental variables.

**Comment by johanmeijer** [comment]
Changes are generic available in master branche.
