### ISSUE TITLE
Docker support wiki entry has typos in sample command line

### ISSUE THREAD

**Issue by benpeart** [johanmeijer/grott#25]
The docker support wiki entry is incorrect (https://github.com/johanmeijer/grott/wiki/Docker-support)

  docker run -d --network=host --restart on-failure -e gnomqtt="True" -e gblockcmd="True" -e pvoutput="True" -e gpvapikey="apikey" -e pvsystemid="systemid" ledidobe/grott
  
should read

  docker run -d --network=host --restart on-failure -e gnomqtt="True" -e gblockcmd="True" -e gpvoutput="True" -e gpvapikey="apikey" -e gpvsystemid="systemid" ledidobe/grott
  
(note the missing leading "g" on pvoutput and pvsystemid).

**Comment by johanmeijer** [comment]
Thanks I will change that

**Comment by johanmeijer** [comment]
@benpeart

 I changed it. This issue can be closed if you agree?

**Comment by benpeart** [comment]
Looks great - thank you
