### ISSUE TITLE
Feature request: Keep MQTT session persistent

### ISSUE THREAD

**Issue by Caros2017** [johanmeijer/grott#264]
For each message from Grott (and Grottserver) the MQTT session is established and then disconnected. This gives a lot of unnesecary traffic especially when being used in combination with Grottserver and faster timers for updates.

I would prefer a persistant MQTT session. Maybe even an option to choose between these two in ENV variables.

**Comment by johanmeijer** [comment]
I will add that in a new version. A parameter (environment variable) to enable/disable seems to be a good solution.

**Comment by johanmeijer** [comment]
Is avalaible and can be enabled by the mqttretain=True paramater (or docker -e gmqttretain="True")
