### ISSUE TITLE
Add API to change operating mode and respective parameters

### ISSUE THREAD

**Issue by Jansza** [johanmeijer/grott#268]
Hello!

This looks like a promising little app to have more control over my Growatt inverter.
I looked over the code and noticed it lacked any means to change the inverter's operating mode and schedules.
Would it be addable?

Growatt's website and mobile app are atrocious. A local API to programmatically change the modes' schedules would be super!

**Comment by johanmeijer** [comment]
At this moment the api functionality is part of grottserver (replaces the growatt server on internet).

Grottserver is being developed but works fine in the beta Version (I Use it for months now). You van find more information about it in discussion #98.

Maybe in the future if grottserver is integrated with grott the api will be available running in proxy mode also.

**Comment by camelcamro** [comment]
that is what it means .... use the newest version, which is also a proxy, so, it is operating:
1.) sending data to your local grott server +
2.) (proxy) also forwarding all data to official growatt server (also working for pvbutler, which using the same techno and is from same company)
so, that means,m you can also change on official server the settings of the logger, and then it will send the data back to the local grott server, which also send it to your client(inverter data logger)
