### ISSUE TITLE
Hosted Grott/AWS

### ISSUE THREAD

**Issue by thorstenfleischmann** [johanmeijer/grott#316]
Would it be possible/advisable to run Grott on aws?

 I like to use Grott for pvoutput.org and change protection

**Comment by rany2** [comment]
@thorstenfleischmann No it is no advisable. If you do, anyone could connect to it and spam your DB/submit on your behalf to PVOutput/etc. There is no authentication when it comes to inverter id so it could also be spoofed and your influxdb records for your inverter could be ruined.

tl;dr keep it on your local network only, if you're going to insist on doing it on AWS at least do it over a site-to-site VPN or setup firewall rules to allow connections from your network ONLY

**Comment by thorstenfleischmann** [comment]
Thanks! How is the logger authenticated at Growatt? Don't we have the same problems with the Growatt servers?

**Comment by rany2** [comment]
@thorstenfleischmann You provide Growatt with a check code that Growatt tied to your SN. Not very secure...

**Comment by rany2** [comment]
@thorstenfleischmann There is no authentication actually... anyone could contact Growatt's servers, spoof your SN and cause you to have fake data

**Comment by johanmeijer** [comment]
Luckily for us it is not that good protect so Grott is able intercept and decode the data. 

For Grott (grottserver) I can implement IP-filtering (Check your public IP address). Dat make a a little bit more secure if you want to run it in AWS (or other Public cloud).  I know this is not a total secure solution but it might help a little bit.

**Comment by thorstenfleischmann** [comment]
> For Grott (grottserver) I can implement IP-filtering (Check your public IP address). Dat make a a little bit more secure if you want to run it in AWS (or other Public cloud). I know this is not a total secure solution but it might help a little bit.

I'm not very familiar with aws but I think they already have something like this built in ("security groups").

**Comment by kreotak** [comment]
> I'm not very familiar with aws but I think they already have something like this built in ("security groups").
Yes, IP filtering should be possible on AWS side. Do you just want to avoid a "local" instance ? Or do you want to have one central instance for multiple inverter locations ?

**Comment by thorstenfleischmann** [comment]
I thought of hosting it for me and maybe a friend.

But finally I concluded that aws is to expensive and I managed to run it natively on my low budget Synology.

But I like the idea of Grott as a service... The friend of mine has no Pi/Synology or anything running.
