### ISSUE TITLE
incorrect values grott-server

### ISSUE THREAD

**Issue by T1gg1** [johanmeijer/grott#333]
Hello,

I started a grott-server in a Dockercontainer and that works fine BUT.....
I started the container and it shows me onetime the correct output but the following updates shows not the correct output.
for example:
First start pvpowerout: 220watt
next update pvpowerout: 20watt.......(proxymode) in the growatt app it shows 225watt and on the inverter the same....225watt
how can that be?

![pv1](https://user-images.githubusercontent.com/77970513/235093487-53f18f2a-307b-408d-9c8b-5803825f9dc1.png)
![pv2](https://user-images.githubusercontent.com/77970513/235093493-ac0701f3-4cc3-4033-b8c2-3fdf70ea18ac.png)

**Comment by T1gg1** [comment]
I guess they were statusmessages because they come nearly seconds. Now the inverter send every 5 minutes a message and that is correct.

**Comment by johanmeijer** [comment]
@T1gg1 it were probably "buffered"(Historical) records. IF I looked at the time it says it was a record from 07:46...

**Comment by T1gg1** [comment]
OMG THank you :D yeah I should read exactly :D
