### ISSUE TITLE
AttributeError: 'IPv4' object has no attribute 'proto'

### ISSUE THREAD

**Issue by hofikhof** [johanmeijer/grott#343]
May 25 09:37:09 aaa grott[703527]: Traceback (most recent call last):
May 25 09:37:09 aaa  grott[703527]:   File "/home/pi/grott/grott.py", line 47, in <module>
May 25 09:37:09 aaa grott[703527]:     sniff.main(conf)
May 25 09:37:09 aaa grott[703527]:   File "/home/pi/grott/grottsniffer.py", line 38, in main
May 25 09:37:09 aaa grott[703527]:     if self.ipv4.proto == 6:
May 25 09:37:09 aaa grott[703527]: AttributeError: 'IPv4' object has no attribute 'proto'

**Comment by rany2** [comment]
try, 

`if hasattr(self.ipv4, 'proto') and self.ipv4.proto == 6`:

**Comment by johanmeijer** [comment]
Can we close this one?

**Comment by hofikhof** [comment]
> Can we close this one?
