### ISSUE TITLE
password for Growatt Shinelink/-X

### ISSUE THREAD

**Issue by wjansenw** [johanmeijer/grott#348]
Hi,
My host running grott has changed IP due to a power outage. 
On the longer run - I will probably move it to have a fixed ip. But that does not solve my current issue:

I am no longer able to login to the growatt shinelink web server to change the IP of the grott host.
Default pwd is admin:admin right? Has anything changed (new firmware?) which caused the pwd to stop working?

Any advice is welcome!
Wim

**Comment by rany2** [comment]
I recall that the username was admin and password was 12345678 not admin/admin.

**Comment by rany2** [comment]
how about just leave the password field empty?

**Comment by wjansenw** [comment]
nothing... I wonder if a reset of the device would allow me to change the IP...

**Comment by rany2** [comment]
maybe,but the only passwords i'm aware that growatt  uses are admin/admin, admin and no pass, and admin/12345678... so in all likelihood it was changed

**Comment by wjansenw** [comment]
Resetting the link did not reset the password... I can't remember me having updated the password. Is that even possible?
I could assume an automated firmware update changed the default settings?

**Comment by johanmeijer** [comment]
Did you already manage to reset the shinelink / password?

**Comment by wjansenw** [comment]
Reset didn't fix the pwd. But I managed to change the ip of the grott host
back to original. So it's working now.... I'll need to live with not
knowing the pwd I guess...

Op do 8 jun. 2023 21:23 schreef Johan Meijer ***@***.***>:

**Comment by johanmeijer** [comment]
Hmm ok. You can change the IP address via the dialogues at the growatt website as well. But that will be tricky as well while you need a active communication at that moment (and afterwards with a grott instance at the new IP address). 

I gave my Raspberry PI  with Grott a static IP address in my router. Just to be save ;)

**Comment by dennismeijer84** [comment]
Same issue over here. After some issues today with the connection/data stream, I've tried to push an update using the Growatt website. After it mentioned 'Update succesfull" I wasn't able to login with admin/admin anymore. (minutes before I could enter the Shinelink with admin/admin.

**Comment by johanmeijer** [comment]
Ok. It might be a good idea to prevent the dataloggers (e.g shinelink)  from updating. 

This can be achieve with Grott  by setting blockcmd = True parameter.

**Comment by cyberdiamond** [comment]
I have found the same with the update from  version 7.0.0.8 to version 7.0.0.9
I don't like being locked out of any device so I will figure out the new password.

@wjansenw @dennismeijer84 or anyone else with a shinelink
I am also trying to work out if anyone with a shinelink can use the grottserver mode and read from the inverter, have any of you tested that?

I can read and set the datalogger settings through grottserver so that is also another way to change the ip address if you need to.

If so can you let me know if it did or did not work before I go digging too much.

**Comment by airtitanium** [comment]
Hi, all who has updated their ShineLink, in my case with version 7.0.0.9 new password for "admin" user is not admin, is  the CC code that  appears behind/bottom of the Datalogger (next to Serial Number/SN).

**Comment by cyberdiamond** [comment]
I did manage to crack the password and was able to log into it.

But it is not the same as the CC code on the sticker on the base of the ShineLanBox which I just tried and that one also works.
The CC one I presume is the prefilled in one (hidden by dots) on the Datalogger Setting page >  login password box.

**Comment by cyberdiamond** [comment]
I can now also 100% confirm the CC one is definitely is the prefilled in one (hidden by dots) on the Datalogger Setting page > login password box.

**Comment by cyberdiamond** [comment]
Also for those that are remote from it or it is not easy to get to the bottom of the ShineLanBox, before updating the firmware you can get the CC (Check Code) from the System Management page > Datalogger Information.

**Comment by dennismeijer84** [comment]
Thanks for your time investiging this topic, and can confirm the CC code is the password in my case.The CC code on the sticker at the unit, as well as within the datalogger settings are the same in my case.
