### ISSUE TITLE
Home Assistant yaml files to expose the Grott entities

### ISSUE THREAD

**Issue by jerommeke-bos** [johanmeijer/grott#35]
Dear Johan,

Thank you for your great work.

Attached you'll find a zip file that contains yaml 
files that will expose all the entities from Grott to HA, inculding some dummy sensors for the type of the inverter and the type and serial number of the datalogger (These should be set by hand):

- sensors_grott_eng.yaml (english version)
- sensors_grott_eng.yaml (dutch version)

The only thing that has to be done in HA is:

- Create a folder in the homeassitant folder named "sensors"
- Copy, when exists, the sensors.yaml file into the newly created directory or move your senors to a file named "sensors.yaml" into the the newly created directory.
- Add the "sensors_growatt_eng.yaml" or "sensors_growatt_nl.yaml" file to the the newly created directory.
- Add or replace the "sensor:" to "sensor: !include_dir_merge_list sensors/"
- Restart HA and the new sensors will be available, you'll find them on within the entities list (search for growatt).

For more information, see: [https://www.home-assistant.io/docs/configuration/splitting_configuration/](https://www.home-assistant.io/docs/configuration/splitting_configuration/)

All has been tested with the latest docker version of Grott , a MIN 4200TL-XE inverter and ShineLink X datalogger.

Best regards,

Jeroen Bos

[sensors_growatt.zip](https://github.com/johanmeijer/grott/files/5793135/sensors_growatt.zip)

**Comment by johanmeijer** [comment]
Hello Jeroen. 

Thank you for the input. I will add the files to github repository and will add the information to the Wiki.

**Comment by johanmeijer** [comment]
@jerommeke-bos 

I add the sensor yaml file to the repository
https://github.com/johanmeijer/grott/tree/master/examples/Home%20Assistent

The wiki is updated: 
https://github.com/johanmeijer/grott/wiki/Home-Assistant-configuration-examples

**Comment by johanmeijer** [comment]
@jerommeke-bos I think this issue can be closed?

**Comment by jerommeke-bos** [comment]
Thank you, Johan
