### ISSUE TITLE
Sensors getting suddenly unavailable 

### ISSUE THREAD

**Issue by thoompje** [johanmeijer/grott#429]
Can anyone help me? Suddenly a lot of sensors getting unavailable

Edit: Now the sensors are gone, yesterday it worked. They are more important then the MQTT ones which are there. Because the output I need for calculations. The **pvpowerout** and lot of other values i am missing ... Who can help me.

![image](https://github.com/johanmeijer/grott/assets/37865789/d231e5f3-98fd-4a31-9143-4f26457b1929)

![image](https://github.com/johanmeijer/grott/assets/37865789/f50d35ea-8429-4b34-ad6e-fde163319fda)

	 - Grott data record date/time processing started
	 - date-time:  2023-10-03T13:18:43
	 - Grott values retrieved:
		 -  datalogserial        :  XXXXXXXXX
		 -  pvserial             :  XXXXXXXXX
		 -  pvstatus             :  1
		 -  pvpowerin            :  853.2
		 -  pv1voltage           :  351.1
		 -  pv1current           :  2.4
		 -  pv1watt              :  853.2
		 -  pv2voltage           :  0.0
		 -  pv2current           :  0.0
		 -  pv2watt              :  0.0
		 -  pvpowerout           :  836.2
		 -  pvfrequentie         :  50.0
		 -  pvgridvoltage        :  243.7
		 -  pvgridcurrent        :  3.2
		 -  pvgridpower          :  843.2
		 -  pvgridvoltage2       :  0.0
		 -  pvgridcurrent2       :  0.0
		 -  pvgridpower2         :  0.0
		 -  pvgridvoltage3       :  0.0
		 -  pvgridcurrent3       :  0.0
		 -  pvgridpower3         :  0.0
		 -  totworktime          :  7533.2
		 -  pvenergytoday        :  1.9
		 -  pvenergytotal        :  6484.8
		 -  epvtotal             :  6562.5
		 -  epv1today            :  1.9
		 -  epv1total            :  6562.5
		 -  epv2today            :  0.0
		 -  epv2total            :  0.0
		 -  pvtemperature        :  43.0
		 -  pvipmtemperature     :  47.6
	 - MQTT jsonmsg: 
			 {"device": "XXXXXXXXX", "time": "2023-10-03T13:18:43", "buffered": "no",
			 "values": {"datalogserial": "XXXXXXXXX", "pvserial": "XXXXXXXXX",
			 "pvstatus": 1, "pvpowerin": 8532, "pv1voltage": 3511, "pv1current": 24,
			 "pv1watt": 8532, "pv2voltage": 0, "pv2current": 0, "pv2watt": 0,
			 "pvpowerout": 8362, "pvfrequentie": 4997, "pvgridvoltage": 2437,
			 "pvgridcurrent": 32, "pvgridpower": 8432, "pvgridvoltage2": 0,
			 "pvgridcurrent2": 0, "pvgridpower2": 0, "pvgridvoltage3": 0,
			 "pvgridcurrent3": 0, "pvgridpower3": 0, "totworktime": 54238882,
			 "pvenergytoday": 19, "pvenergytotal": 64848, "epvtotal": 65625, "epv1today":
			 19, "epv1total": 65625, "epv2today": 0, "epv2total": 0, "pvtemperature":
			 430, "pvipmtemperature": 476}}
	 - Grott MQTT topic used : energy/growatt
	 - MQTT send failed: [Errno 99] Address not available
	 - Grott Send data to PVOutput disabled 
	 - Grott Send data to Influx disabled 
	 - Grott extension processing started :  grott_ha
	 - Grott extension processing ended :  0

	 - Growatt packet received:
		  <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.30.33.9', 5279), raddr=('172.25.1.105', 16959)>
	 - Data less then minimum record length, data not processed

Yaml file of the Addon

```
gmode: proxy
gnomqtt: false
ginvtype: default
mqtt:
  host: localhost
  port: 1883
  username: xxxxx
  password: xxxxx
gpvoutput: false
```

**Comment by thoompje** [comment]
This message: 'MQTT send failed: [Errno 99] Address not available' is weird because data is getting updated the only thing is that i miss some sensors...

**Comment by thoompje** [comment]
> I'm not expert but I don't think it is publishing things to MQTT based on what that error message is saying.

But its weird that the other sensors are updating and being published in MQTT, maybe @johanmeijer knows more about this how it works?

**Comment by thoompje** [comment]
It looks like that he now takes the first 9 values and not doing anything with the rest.

**Comment by thoompje** [comment]
Alright All, I think I found the problem/challenge. I was deep diving into the problem with MQTT explorer as well and  find out that the connection were cut off after a bit of data was send.

So i stopped Zigbee2mqtt Edge and zigbee2mqttassistant-dev, after that i restarted the Grott - HA extension addon and suddenly all the sensors came in. So it looks like Mosquitto broker is to busy on my PI4 (with SSD). Maybe something for the addon to edit to send data in batches?

**Comment by muppet3000** [comment]
@thoompje  - Just as an option - If you install the https://github.com/muppet3000/homeassistant-grott integration and disable the grott_ha one you're using, you'll get a lot more of the data available in HA.
Just an option.

**Comment by thoompje** [comment]
@muppet3000 Thanks had this one installed before with the gorwatt connection, was working great! for now this is working and i'll keep an eye on it! Thanks all.

**Comment by Vinisz** [comment]
> @thoompje - Just as an option - If you install the https://github.com/muppet3000/homeassistant-grott integration and disable the grott_ha one you're using, you'll get a lot more of the data available in HA. Just an option.

![image](https://github.com/johanmeijer/grott/assets/49644964/5ccc75cd-5750-4d03-abab-ad093030cdc5)

**Comment by muppet3000** [comment]
> > @thoompje - Just as an option - If you install the https://github.com/muppet3000/homeassistant-grott integration and disable the grott_ha one you're using, you'll get a lot more of the data available in HA. Just an option.
> 
> ![image](https://user-images.githubusercontent.com/49644964/272596605-5ccc75cd-5750-4d03-abab-ad093030cdc5.png)

It's not an add-on, it's an integration for displaying the information that's published to MQTT by grott.

**Comment by thoompje** [comment]
> > > @thoompje - Just as an option - If you install the https://github.com/muppet3000/homeassistant-grott integration and disable the grott_ha one you're using, you'll get a lot more of the data available in HA. Just an option.
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/49644964/272596605-5ccc75cd-5750-4d03-abab-ad093030cdc5.png)
> 
> 
> 
> It's not an add-on, it's an integration for displaying the information that's published to MQTT by grott.

Question, I don't get any data in the intergration? ![image](https://github.com/johanmeijer/grott/assets/37865789/457c8c1d-28f0-4a08-8fbc-da4f4fa2a620)

With the + as well with the devicenumber/serial number. What can be wrong? So less to check or configure.

**Comment by muppet3000** [comment]
Have you configured MQTT in Home assistant correctly?

Have you told Grott to publish to MQTT?

What do the Grott logs show?

**Comment by thoompje** [comment]
> Have you configured MQTT in Home assistant correctly?
> 
> 
> 
> Have you told Grott to publish to MQTT?
> 
> 
> 
> What do the Grott logs show?

Only thing is that I could not co figure anonymous access in mqtt. Is there a workaround for?

**Comment by muppet3000** [comment]
> > Have you configured MQTT in Home assistant correctly?
> > Have you told Grott to publish to MQTT?
> > What do the Grott logs show?
> 
> Only thing is that I could not co figure anonymous access in mqtt. Is there a workaround for?

It depends how you're running MQTT, by default it's anonymous.

**Comment by muppet3000** [comment]
> > @thoompje - Just as an option - If you install the https://github.com/muppet3000/homeassistant-grott integration and disable the grott_ha one you're using, you'll get a lot more of the data available in HA. Just an option.
> 
> Hi, I am using this Integration ( https://github.com/muppet3000/homeassistant-grott ) and the inverter is publishing to Grot and relaying to Shine, I am receiving MQTT traffic to HA, but not Battery% and Export to Grid , but I can see that the Shine App is getting this info . Does Grot only relay a subset of data to MQTT ? Thanks

It depends on what type of inverter you have, you need to choose the correct value for `invtype` in the grott.ini file. The options are: `default,sph,spf,max,tl3`

**Comment by thoompje** [comment]
> > > Have you configured MQTT in Home assistant correctly?
> > > Have you told Grott to publish to MQTT?
> > > What do the Grott logs show?
> > 
> > 
> > Only thing is that I could not co figure anonymous access in mqtt. Is there a workaround for?
> 
> It depends how you're running MQTT, by default it's anonymous.

Its not here
![image](https://github.com/johanmeijer/grott/assets/37865789/5e56e95a-e59d-4ada-a8af-a157b5c957c9)

And i cannot edit mosquitto to anonymous, thats something they deleted from it. Also with MQTT Explorer i cannot connect without credentials. If you know how to edit it to anonymous that would be great.

**Comment by muppet3000** [comment]
> > > > Have you configured MQTT in Home assistant correctly?
> > > > Have you told Grott to publish to MQTT?
> > > > What do the Grott logs show?
> > > 
> > > 
> > > Only thing is that I could not co figure anonymous access in mqtt. Is there a workaround for?
> > 
> > 
> > It depends how you're running MQTT, by default it's anonymous.
> 
> Its not here ![image](https://user-images.githubusercontent.com/37865789/272816110-5e56e95a-e59d-4ada-a8af-a157b5c957c9.png)
> 
> And i cannot edit mosquitto to anonymous, thats something they deleted from it. Also with MQTT Explorer i cannot connect without credentials. If you know how to edit it to anonymous that would be great. Here they say also that it is deleted from Mosquitto [home-assistant/addons#2623](https://github.com/home-assistant/addons/issues/2623)

I run mosquitto outside of Home Assistant and have the following config:
```
allow_anonymous true
listener 1883
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
```
Given that it's siloed off from the rest of my network it's not really an issue for me.

**Comment by RVis78** [comment]
Can somebody maybe help me to install Grott > MQTT step by step in Dutch - NEDERLANDS

I already installed integration:
MQTT broker (core-mosquitto)
Grott (empty configuration) - where to find my Device id, while the + will not work! No entities are added!

Add-on:
Zigbee2MQTT installed to use zigbee devices such as motion detection and light.

I am confused because at 

    muppet3000
    /
    homeassistant-grott

use docker, while i allready have grott installed (visible in HA > Integrations)

Please can anybody help me, if possible step by step in DUTCH

**Comment by muppet3000** [comment]
@RVis78 - How have you installed Grott? I see from this message that you have installed the home-assistant integration, but have you installed the actual program Grott?
Are you running HomeAssistant OS? If so, you have access to add-ons and I can give you a simple link to help get it installed through that.

**Comment by RVis78** [comment]
Hi Chris,Thanks for your reply! Yes I run HA OS on a RPi4, as add-on I installed Grott, but I don’t have any idea how to install the actual program Grott! I would like to receive the single link, because I don’t have enough experience with installing it as docker, or phyton program.Thanks a lot in advance!Met vriendelijke groet,Remco VisserOp 9 okt. 2023 om 22:03 heeft Chris Straffon ***@***.***> het volgende geschreven:﻿
@RVis78 - How have you installed Grott? I see from this message that you have installed the home-assistant integration, but have you installed the actual program Grott?
Are you running HomeAssistant OS? If so, you have access to add-ons and I can give you a simple link to help get it installed through that.

**Comment by muppet3000** [comment]
You can run Grott (the program) as an add-on using this repository: https://github.com/egguy/grott-home-assistant-add-on

Note, when you install it you need to make the following choices:
1. Use the 'edge' version when you install it
2. Check `enable grott MQTT`
3. Disable `HA integration`

Then data will flow into MQTT and the home-assistant grott integration will pick up the values and display them for you.

**Comment by RVis78** [comment]
﻿I’ve already run/install the program as described! I also forwarded the information on the inverter side (by adding the right ip address) enabled Grott MQTT and disabled HA integration. But there are no extra entities available in my MQTT configuration. What else can I try?Op 9 okt. 2023 om 22:32 heeft Chris Straffon ***@***.***> het volgende geschreven:﻿
You can run Grott (the program) as an add-on using this repository: https://github.com/egguy/grott-home-assistant-add-on
Note, when you install it you need to make the following choices:

Use the 'edge' version when you install it
Check enable grott MQTT
Disable HA integration

Then data will flow into MQTT and the home-assistant grott integration will pick up the values and display them for you.

**Comment by muppet3000** [comment]
Can you please share the output from the grott service then? We should be able to see the output processing messages from your inverter and forwarding them on to MQTT in there.

**Comment by RVis78** [comment]
Hi again, I reinstalled everything once again! Don’t have any clue how? But it works!Met vriendelijke groet,Remco VisserOp 10 okt. 2023 om 07:24 heeft Chris Straffon ***@***.***> het volgende geschreven:﻿
Can you please share the output from the grott service then? We should be able to see the output processing messages from your inverter and forwarding them on to MQTT in there.

**Comment by muppet3000** [comment]
> Hi again, I reinstalled everything once again! Don’t have any clue how? But it works!Met vriendelijke groet,Remco VisserOp 10 okt. 2023 om 07:24 heeft Chris Straffon ***@***.***> het volgende geschreven:﻿ Can you please share the output from the grott service then? We should be able to see the output processing messages from your inverter and forwarding them on to MQTT in there. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

hahahaha, that's brilliant. I'd just take that as a 'win' and get on with life :D 

Glad you've got it working now.
