### ISSUE TITLE
Support Shinemaster

### ISSUE THREAD

**Issue by andynnd** [johanmeijer/grott#43]
Hi All, do you have any plan to support Shinemaster?

**Comment by johanmeijer** [comment]
I have not had the request untill know.

Did you tried it?. The shinemaster seems to collect and send data to the growatt server the same way the shinelink does. It migh create data records that grott recognizes. 

If you want to invest some time in it we can try to make it work.

**Comment by johanmeijer** [comment]
@andynnd Did you already try Grott with the shinemaster?
