### ISSUE TITLE
Cannot reach datalogger anymore

### ISSUE THREAD

**Issue by kmroumen** [johanmeijer/grott#430]
Due to the constant issues with the Growatt API I tried to setup Grott & MQTT for integration in Home assistant. I've installed Grott via Python on a Ubuntu machine, along with mosquito. Then I've altered the IP address for my Datalogger via server.growatt.com (successfully), but now it's disconnected from growatt.com and no MQTT messages seem to be coming in. I think my Ubuntu-machine IP changed (forgot to make it static earlier), but there's no way to alter it on growatt.com anymore. Resetting of the ShineLanBox has no result (cloud icons flickers on and off). Is there any other way to restore my previous configuration?

![CleanShot 2023-10-03 at 18 23 08@2x](https://github.com/johanmeijer/grott/assets/28234/d44bed12-9bc2-474f-a844-89c08fe1e36d)
 

![CleanShot 2023-10-03 at 18 21 50@2x](https://github.com/johanmeijer/grott/assets/28234/0dab1078-a507-4169-a54e-fdc1b49b0733)

![CleanShot 2023-10-03 at 18 17 59@2x](https://github.com/johanmeijer/grott/assets/28234/007c3fb3-300c-42b6-bb18-7ce139d61010)

**Comment by johanmeijer** [comment]
Updating the shinelanbox should work. 

You can either set an url (need to enable this I think) or a ip adress. 

Can you see in the grott log (systemlog with journalctl) if grott receives data?

**Comment by kmroumen** [comment]
Thanks, got access to the datalogger again and tried to update it using the correct IP address. Had no success message, but logger is offline again in server.growatt.com. Output of journalctl: https://pastebin.com/yb0aWin0

Seems good, right? Doesn't show up in MQTT explorer though.

**Comment by johanmeijer** [comment]
I do not see any communication yet through grott 

Do you see any data at the growatt website?

**Comment by kmroumen** [comment]
I found that trying to alter the config using the ShineLanBox web interface was working way better than via server.growatt.com. The IP address of my Grott-server was not updated correctly. Was able to update it via the web interface and now data comes in nicely and is processed as it should. Thanks for your help and your great work!

**Comment by johanmeijer** [comment]
Can we close this one?
