### ISSUE TITLE
Invalid records in the communication with Growatt 6000TL3-S

### ISSUE THREAD

**Issue by altserg** [johanmeijer/grott#432]
I have Growatt 6000TL3-S 3 phase inverter with serial JNE4A140B5. 

When I do not set the inverter type in grott.ini, I receive MQTT messages but there are errors in the Growatt data parsing, see below
- Inverter serial not recognized - using inverter type default.
- Data less then minimum record length, data not processed
- Grott data ack record or data record not defined no processing done

When I set the inverter type to TLX, I receive no MQTT data, and the look looks like 2nd log below.

**MQTT message when invertor type is not set or set to generic**
{"device": "JNE4A140B5", "time": "2023-10-03T16:49:10", "buffered": "no", "values": {"datalogserial": "DELETED", "pvserial": "JNE4A140B5", "pvstatus": 1, "pvpowerin": 6040, "pv1voltage": 3401, "pv1current": 9, "pv1watt": 3060, "pv2voltage": 2980, "pv2current": 10, "pv2watt": 2980, "pvpowerout": 5630, "pvfrequentie": 4993, "pvgridvoltage": 4062, "pvgridcurrent": 10, "pvgridpower": 2340, "pvgridvoltage2": 4093, "pvgridcurrent2": 9, "pvgridpower2": 2122, "pvgridvoltage3": 4062, "pvgridcurrent3": 10, "pvgridpower3": 2340, "pvenergytoday": 62, "pvenergytotal": 183548, "totworktime": 93620845, "pvtemperature": 336, "pvipmtemperature": 368, "epv1today": 37, "epv1total": 109628, "epv2today": 34, "epv2total": 96168, "epvtotal": 205796}}

**Generic invertor type log:**
`- Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 49626), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed
         
         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 49626), raddr=('47.91.67.66', 5279)>
         - Growatt original Data:
                 \x00\x0e\x00\x06\x01\x01\x01\x04\x0d\x22\x2c\x41\x20\x46\x44\x71\x31\x59\x77
                 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
                 \x25\x39\x24\x40\x35\x76\x46\x5f\x35\x54\x74\x74\x47\x72\x6f\x77\x61\x74\x74
                 \x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x76\x7e\x70\x4f\x58\x7a\x75\x61
                 \x74\x74\x6b\x72\x6e\x77\x61\x78\x05\x4b\x05\x6f\x72\x61\x74\x72\x7c\x7e\x02
                 \x77\x64\x74\x74\x41\x44\x6f\x77\x6a\x54\x67\xce\x62\x74\x77\x69\x74\x74\x40
                 \x1e\x7f\x59\x61\x7c\x74\x47\x75\x1a\x67\x62\x74\x7c\x47\x72\x68\x16\x61\x74
                 \x74\x47\x72\x6d\xba\x67\x71\xe0\x92\x40\x6e\x6d\x61\x74\x74\x47\x72\x6f\x77
                 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x75\x07\x7e\x4e\x7b\x2b\x74\x74\x47\x5f
                 \x6f\x2e\x2f\x54\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x73\xc3\x35\x61\x74\x74
                 \x47\x72\x6e\x00\xcf\x74\x77\x64\x82\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61
                 \x74\x74\x47\x72\x6f\x77\x61\x70\x74\x47\x98\x0f\x77\x61\x74\x74\x47\x72\x6f
                 \x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
                 \x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x32\x65
         - Grott automatic protocol detection
         - Grott data record length 265
         - layout   :  T060104
         - no matching record layout found, try generic
         - Record layout used :  T06NNNN
         - Grott Growatt data decrypted
         - Growatt plain data:
                 000e0006010101044a50433641323036433600000000000000000000000000000000000000004
                 a4e45344131343042350000000000000000000000000000000000000000170a04082a15020000
                 002c000100000c710c7700050000063b0c6d00050000063600000b201389101b00080000076c1
                 02e0008000007751003000800000761000000000002cd060594d532011a000000000000000000
                 0000000000000001400c210c4a0000002d00594e2000000000000000000001ac4200000000000
                 177ae000323f00000000000000000000000000000000000040000ea6000000000000000000000
                 00000000000000000000000000000000000000000000000000000000000000004504
         - Possible Inverter serial JNE4A140B5
         - Inverter serial not recognised - using inverter type default
         - Growatt new layout processing
                 - decrypt       :  True
                 - offset        :  6
                 - record layout :  T06NNNN

         - Grott data record date/time processing started
         - date-time:  2023-10-04T08:42:21
         - Grott values retrieved:
                 -  datalogserial        :  HIDDEN
                 -  pvserial             :  JNE4A140B5
                 -  pvstatus             :  1
                 -  pvpowerin            :  318.5
                 -  pv1voltage           :  319.1
                 -  pv1current           :  0.5
                 -  pv1watt              :  159.5
                 -  pv2voltage           :  318.1
                 -  pv2current           :  0.5
                 -  pv2watt              :  159.0
                 -  pvpowerout           :  284.8
                 -  pvfrequentie         :  50.0
                 -  pvgridvoltage        :  412.3
                 -  pvgridcurrent        :  0.8
                 -  pvgridpower          :  190.0
                 -  pvgridvoltage2       :  414.2
                 -  pvgridcurrent2       :  0.8
                 -  pvgridpower2         :  190.9
                 -  pvgridvoltage3       :  409.9
                 -  pvgridcurrent3       :  0.8
                 -  pvgridpower3         :  188.9
                 -  pvenergytoday        :  0.0
                 -  pvenergytotal        :  18355.8
                 -  totworktime          :  13005.6
                 -  pvtemperature        :  28.2
                 -  pvipmtemperature     :  32.0
                 -  epv1today            :  0.0
                 -  epv1total            :  10963.4
                 -  epv2today            :  0.0
                 -  epv2total            :  9617.4
                 -  epvtotal             :  20580.8
         - MQTT jsonmsg:
                         {"device": "JNE4A140B5", "time": "2023-10-04T08:42:21", "buffered": "no",
                         "values": {"datalogserial": "HIDDEN", "pvserial": "JNE4A140B5",
                         "pvstatus": 1, "pvpowerin": 3185, "pv1voltage": 3191, "pv1current": 5,
                         "pv1watt": 1595, "pv2voltage": 3181, "pv2current": 5, "pv2watt": 1590,
                         "pvpowerout": 2848, "pvfrequentie": 5001, "pvgridvoltage": 4123,
                         "pvgridcurrent": 8, "pvgridpower": 1900, "pvgridvoltage2": 4142,
                         "pvgridcurrent2": 8, "pvgridpower2": 1909, "pvgridvoltage3": 4099,
                         "pvgridcurrent3": 8, "pvgridpower3": 1889, "pvenergytoday": 0,
                         "pvenergytotal": 183558, "totworktime": 93639986, "pvtemperature": 282,
                         "pvipmtemperature": 320, "epv1today": 0, "epv1total": 109634, "epv2today":
                         0, "epv2total": 96174, "epvtotal": 205808}}
         - Grott MQTT topic used : energy/growatt
         - MQTT message message sent
         - Grott Send data to PVOutput disabled
         - Grott Send data to Influx disabled
         - Grott extension processing disabled

         - Growatt packet received:
                  <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 5279), raddr=('192.168.2.110', 23852)>
         - Data less then minimum record length, data not processed
         - Growatt original Data:
                 \x00\x07\x00\x06\x01\x01\x01\x03\x0d\x22\x2c\x41\x20\x46\x44\x71\x31\x59\x77
                 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
                 \x25\x39\x24\x40\x35\x76\x46\x5f\x35\x54\x74\x74\x47\x72\x6f\x77\x61\x74\x74
                 \x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x76\x7e\x70\x4f\x41\x74\x75\x61
                 \x74\x74\x6b\x73\x6e\x77\x61\x74\x74\x47\x16\x6f\x88\x9e\x8b\x74\x47\x98\x0f
                 \x60\x11\x30\x3f\x76\x5c\x5f\x5a\x23\x32\x44\x69\x42\x4f\x77\x60\x74\x74\x42
                 \x0a\x6f\x4b\x6d\xf0\x65\x59\x60\xe1\x63\x7f\x3e\x3a\x02\x46\x2e\x46\x55\x44
                 \x36\x72\x52\x7f\x86\x00\x74\x75\x47\x72\x6f\x77\x61\x74\x74\x47\x7e\xeb\x66
                 \x84\x66\xfa\x53\x6c\x62\x4d\x70\x6a\x66\xd4\x61\xe2\x7f\x60\x76\x77\x47\x5f
                 \x6f\x2e\x66\x93\x74\x4d\x72\x6b\x77\x69\x74\x47\x47\x43\x6f\x45\x61\x46\x74
                 \x75\x72\x5d\x77\x53\x74\x46\x47\x40\x6f\x45\x26\x06\x1b\x30\x13\x1b\x03\x41
                 \x3d\x1a\x31\x17\x1d\x03\x04\x06\x10\x2c\x13\x0e\x47\x54\x44\x41\x47\x72\x6f
                 \x74\x60\x45\x74\x46\x72\x6e\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x75\x67\xdb
                 \x72\x0b\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x3f\xbb
         - Grott automatic protocol detection
         - Grott data record length 265
         - layout   :  T060103
         - no matching record layout found, try generic
         - Record layout used :  T060103
         - Grott Growatt data decrypted
         - Growatt plain data:
                 00070006010101034a50433641323036433600000000000000000000000000000000000000004
                 a4e45344131343042350000000000000000000000000000000000000000170a0408331b020000
                 002c010100000000006400ffffff0000ea601770444b312e302d4246302e30200001000005780
                 03c0c84111e128e141e4a4e45344131343042352010f161000100000000000000000c8411e512
                 8e141e0d3a111e1293138d08010203002d005907e7000a0004000800330031003200320032003
                 2003200320032003247726f7761747420496e766572746572646b616130353035000000030131
                 0001000100000000000000000001139c0064000000000000000000000000000048da
         - Grott data ack record or data record not defined no processing done

**TLX invertor type log:**
`Generic:
        version:                 2.7.8
        verbose:                 True
        trace:                   False
        config file:             grott.ini
        minrecl:                 100
        decrypt:                 True
        compat:                  False
        invtype:                 tlx
        invtypemap:              {}
        include_all:             False
        blockcmd:                False
        noipf:                   False
        time:                    auto
        sendbuf:                 True
        timezone:                local
        valueoffset:             6
        offset:                  6
        inverterid:              automatic
        mode:                    proxy
        grottip                  default
        grottport                5279
_MQTT:
        nomqtt                   False
        mqttip:                  localhost
        mqttport:                1883
        mqtttopic:               energy/growatt
        mqttmtopic:              False
        mqttmtopicname:          energy/meter
        mqttinverterintopic:     False
        mqtttretain:             False
        mqtttauth:               True
        mqttuser:                grott
        mqttpsw:                 **secret**
_Growatt server:
        growattip:               47.91.67.66
        growattport:             5279
_PVOutput:
        pvoutput:                False
        pvdisv1:                 False
        pvtemp:                  False
        pvurl:                   https://pvoutput.org/service/r2/addstatus.jsp
        pvapikey:                yourapikey
        pvinverters:             1
        pvsystemid:              systemid1
_Influxdb:
        influx:                  False
        influx2:                 False
        database:                grottdb
        ip:                      localhost
        port:                    8086
        user:                    grott
        password:                **secret**
        organization:            grottorg
        bucket:                  grottdb
        token:                   **secret**
_Extension:
        extension:               False
        extname:                 grottext
        extvar:                  {'none': 'none'}

Grott proxy mode started
Hostname : SmartHome
IP :  127.0.1.1 , port :  5279

         - ('192.168.2.110', 38632) has connected

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 5279), raddr=('192.168.2.110', 38632)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 5279), raddr=('192.168.2.110', 38632)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Growatt original Data:
                 \x00\x06\x00\x06\x01\x01\x01\x03\x0d\x22\x2c\x41\x20\x46\x44\x71\x31\x59\x77
                 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
                 \x25\x39\x24\x40\x35\x76\x46\x5f\x35\x54\x74\x74\x47\x72\x6f\x77\x61\x74\x74
                 \x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x42\x64\x70\x4f\x30\x4e\x75\x61
                 \x74\x74\x6b\x73\x6e\x77\x61\x74\x74\x47\x16\x6f\x88\x9e\x8b\x74\x47\x98\x0f
                 \x60\x11\x30\x3f\x76\x5c\x5f\x5a\x23\x32\x44\x69\x42\x4f\x77\x60\x74\x74\x42
                 \x0a\x6f\x4b\x6d\xf0\x65\x59\x60\xe1\x63\x7f\x3e\x3a\x02\x46\x2e\x46\x55\x44
                 \x36\x72\x52\x7f\x86\x00\x74\x75\x47\x72\x6f\x77\x61\x74\x74\x47\x7e\xeb\x66
                 \x84\x66\xfa\x53\x6c\x62\x4d\x70\x6a\x66\xd4\x61\xe2\x7f\x60\x76\x77\x47\x5f
                 \x6f\x2e\x66\x93\x74\x4d\x72\x6b\x77\x69\x74\x5f\x47\x72\x6f\x45\x61\x46\x74
                 \x75\x72\x5d\x77\x53\x74\x46\x47\x40\x6f\x45\x26\x06\x1b\x30\x13\x1b\x03\x41
                 \x3d\x1a\x31\x17\x1d\x03\x04\x06\x10\x2c\x13\x0e\x47\x54\x44\x41\x47\x72\x6f
                 \x74\x60\x45\x74\x46\x72\x6e\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x75\x67\xdb
                 \x72\x0b\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\xf7\x34
         - Grott automatic protocol detection
         - Grott data record length 265
         - layout   :  T060103TLX
         - no matching record layout found, try generic
         - Record layout used :  T060103TLX
         - Grott Growatt data decrypted
         - Growatt plain data:
                 00060006010101034a50433641323036433600000000000000000000000000000000000000004
                 a4e45344131343042350000000000000000000000000000000000000000231004084221020000
                 002c010100000000006400ffffff0000ea601770444b312e302d4246302e30200001000005780
                 03c0c84111e128e141e4a4e45344131343042352010f161000100000000000000000c8411e512
                 8e141e0d3a111e1293138d08010203002d005907e7000a00040008002b0000003200320032003
                 2003200320032003247726f7761747420496e766572746572646b616130353035000000030131
                 0001000100000000000000000001139c006400000000000000000000000000008055
         - Grott data ack record or data record not defined no processing done

         - Growatt packet received:
                  <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 5279), raddr=('192.168.2.110', 38632)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 5279), raddr=('192.168.2.110', 38632)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Data less then minimum record length, data not processed

         - Growatt packet received:
                  <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.2.140', 58158), raddr=('47.91.67.66', 5279)>
         - Growatt original Data:
                 \x00\x0f\x00\x06\x01\x01\x01\x04\x0d\x22\x2c\x41\x20\x46\x44\x71\x31\x59\x77
                 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
                 \x25\x39\x24\x40\x35\x76\x46\x5f\x35\x54\x74\x74\x47\x72\x6f\x77\x61\x74\x74
                 \x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x76\x7e\x70\x4f\x5c\x73\x75\x61
                 \x74\x74\x6b\x72\x6e\x77\x61\x7a\x23\x4a\xfc\x6f\x72\x61\x74\x72\x80\x7e\xf3
                 \x77\x67\x74\x74\x40\xe2\x6f\x77\x6c\x75\x67\xc2\x62\x71\x77\x69\x74\x74\x40
                 \x1f\x7f\x47\x61\x7c\x74\x47\x75\x19\x67\x62\x74\x7c\x47\x72\x68\x16\x61\x74
                 \x74\x46\x72\x6d\xba\x66\x71\xe0\x90\x6b\x6e\x6b\x61\x74\x74\x47\x72\x6f\x77
                 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x75\x05\x7e\x4c\x7b\x30\x74\x74\x47\x5f
                 \x6f\x2e\x2f\x54\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x73\xc3\x35\x61\x74\x74
                 \x47\x72\x6e\x00\xcf\x74\x77\x64\x82\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61
                 \x74\x74\x47\x72\x6f\x77\x61\x70\x74\x47\x98\x0f\x77\x61\x74\x74\x47\x72\x6f
                 \x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
                 \x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x9c\xfa
         - Grott automatic protocol detection
         - Grott data record length 265
         - layout   :  T060104TLX
         - no matching record layout found, try generic
         - no matching record layout found, standard processing performed
         - Record layout used :  none
         - Grott Growatt data decrypted
         - Growatt plain data:
                 000f0006010101044a50433641323036433600000000000000000000000000000000000000004
                 a4e45344131343042350000000000000000000000000000000000000000170a04082e1c020000
                 002c000100000e570d8e0005000006c70c9c00060000079000000d011385101e00080000076d1
                 0300008000007761003000800000761000000010002cd070594d719011c000000000000000000
                 0000000000000001420c230c510000002d00594e2000000000000000000001ac4200000000000
                 177ae000323f00000000000000000000000000000000000040000ea6000000000000000000000
                 0000000000000000000000000000000000000000000000000000000000000000eb9b
         - Grott data ack record or data record not defined no processing done`

**Comment by johanmeijer** [comment]
It seems to be OK for me (using no invtype). The data looks reasonable.

Maybe I write to much information to the log. The messages you see are not error messages but informational (debug for me). Do not worry about that to much. If I have time I will sanitise the messages in a next release (is on the todo list).

**Comment by altserg** [comment]
Better reporting using python logging mechanist and not print() would be very appreciated
Closing the issue as according to the code owner the verbose log looks ok. Let me know if you need more data from my inverter to parse unknown type records in the future
