### ISSUE TITLE
Inverter type and data parsing

### ISSUE THREAD

**Issue by talisker77** [johanmeijer/grott#435]
Serial number, build number and device
![image](https://github.com/johanmeijer/grott/assets/713604/1ef521ce-1450-453b-8de4-c3d4e4939304)
Have selected default for invtype in grott.ini and have serial number EMFHCL900B

To me it seems like data shown in shineapp and on growatt portal differ from the data shown in HA (Home assistant).
I've made a dump of grott log and will attach later.

Question: 
- Is 'default' correct invtype to use or should I select something else.

I appreciate this project and it seems to be working better than the HACS Growatt API after api portal login issue with server.growatt, and hope this data I will attach will help make the project better.

**Comment by talisker77** [comment]
Attached log from grott
[grott.log](https://github.com/johanmeijer/grott/files/12819325/grott.log)
Hope this will help

**Comment by johanmeijer** [comment]
If I look at your data I think you should specify invtype=tl3. 

What model inverter do you have?

**Comment by talisker77** [comment]
My inverter is a mid 6ktl3-xl. I will try that during the day.
Thanks.

**Comment by talisker77** [comment]
![Screenshot_2023-10-06-21-27-05-151](https://github.com/johanmeijer/grott/assets/713604/1e9c681d-02af-4e85-891c-364a30542892)
Looks better now.
