### ISSUE TITLE
Question, is it just monitoring?

### ISSUE THREAD

**Issue by coleburg** [johanmeijer/grott#436]
Looking for a little info please, 

Does this only monitor or can it also change the settings, ie, Bat First, Grid First etc?

Lastly, does it work with SPA3000?

Thank you in advance

**Comment by johanmeijer** [comment]
Hi it should work with SPA 3000 (invtype=spa in the grott.ini).

Grott itself is a proxy and can not change the settings, but ..... Grottserver (a replacement of the growatt server) can. 

For more information see: 
https://github.com/johanmeijer/grott/wiki/Grottserver 
and discussion #98

**Comment by coleburg** [comment]
Amazing, thank you so much
