### ISSUE TITLE
inverter serial not recognized

### ISSUE THREAD

**Issue by annbuw** [johanmeijer/grott#445]
hello @johanmeijer 

i am using the HA grott addon and i have a inverter where the data is displayed wrong with strange values
i have asked muppet3000 also for it but he is thinking the problem occurs in the grott addon.

https://github.com/muppet3000/homeassistant-grott/issues/44#issuecomment-1756092320

to begin , i have 4 inverters and dataloggers , the only problem is the data from the MOD5000TL3-X
the data in the growatt app shinephone is ok for this inverter , so the data which grott send should be fine, but the data in the HA is not.
also i see the following in the logs from grott and mqtt broker.
do you have a solution ? i have tried with grott.ini the MIN , TL3 , SPH , and more but the data stays the same in HA

![Image5](https://github.com/johanmeijer/grott/assets/116624180/99cf3572-2cb0-4913-a584-3e3913359999)

![Image7](https://github.com/johanmeijer/grott/assets/116624180/a9521d10-c66e-4290-9400-82e16582d129)

**Comment by johanmeijer** [comment]
invtype=min should work for een MOD type inverter

**Comment by annbuw** [comment]
thanks , i have 4 inverters , do i have to change it in the grot configuration / options  or in a grott.ini file
if in the config/options do i have to do it in the inverter mapping with the serial from the inverter or in the inverter type for all 4 ?
i have tried it in a grott.ini file but then notting changed

**Comment by annbuw** [comment]
yes , all is now working correct 
put the serial and tl3 in the configuration/options page , min was not working
thanks
