### ISSUE TITLE
Use on mirror port (span port)

### ISSUE THREAD

**Issue by bardahlm** [johanmeijer/grott#480]
I'm trying to figure out Grott can be set up get data from a mirror port that mirrors all traffic to and from the inverter. My plan is to have Grott run on its own interface (eth1 for example) and [configure the switch to mirror all traffic](https://en.wikipedia.org/wiki/Port_mirroring) to and from the ShineLan box to that port.
eth1 will need to be set up in promisq mode and the traffic will have the mac addresses of the default gw and the ShineLan box.
Is this something that can work?

**Comment by johanmeijer** [comment]
I am not sure what you want to do. Seems a little bit complicated to me.  Why not using the "normal" proxy mode of grott (listing at port 5279 and sending the data unchanged to the growatt server)?
