### ISSUE TITLE
Change rule in Wiki to use sudo for paho-mqtt

### ISSUE THREAD

**Issue by Jeltel** [johanmeijer/grott#5]
I'm trying grott on a Pi ZeroW I have laying around. But got stuck on the paho module It keeps saying it wasn't installed. Turns out you have:
`pip3 install paho-mqtt`
That installs paho for the normal user.

Where it should be
`sudo pip3 install paho-mqtt`

Can you change that?

**Comment by johanmeijer** [comment]
changed!
