### ISSUE TITLE
#enhancement add Fan power to SPF inverters 

### ISSUE THREAD

**Issue by tabascoz** [johanmeijer/grott#548]
Hi there! 

Would it be possible to include the Fan1 value readings for SPF inverters? 

this inclusion in grottconf.py after line 942 did the trick

`"BatWatt"           : {"value" :394, "length" : 4, "type" : "numx", "divide" : 10} `

Thanks, Fennando

**Comment by johanmeijer** [comment]
Hi Fennando. I like to at this but if I like in grottconf (2.7.8 and 2.8.3) this is already in there. Do I miss something?

**Comment by tabascoz** [comment]
sorry Lol, posted the wrong line by mistake although i mentioned the right value. 

The right line: 

`"Fan1"              : {"value" :494, "length" : 2, "type" : "num", "divide" : 1}`

I checked and recloned the repo and it is not in v 2.8.3

Cheers

**Comment by johanmeijer** [comment]
Dan. I only called it  invfanspeed (to match the documentation).

**Comment by tabascoz** [comment]
Thanks Johan, all working fine !
