### ISSUE TITLE
MOD 6000TL3-XH recognized but no MQTT to HA

### ISSUE THREAD

**Issue by InvertedMinor** [johanmeijer/grott#551]
Great application, deep respect for all the work.

The data from MOD 6000TL3-XH is flowing into the Grott Beta branch (2.8) Current version: 95acf9c (see below) but no MQTT data is received. I have tried all of the inverter types, min is giving a meaning full data set in the log but not in HA MQTT.

Any suggestions?

Logs below:
 
Grott external record whitelist 'recwl.txt' not found

Grott records whitelisted :  {'5250', '501b', '5216', '5005', '5105', '5116', '0119', '5229', '0120', '5004', '5016', '0150', '5050', '5119', '5129', '0105', '5003', '5219', '5104', '0103', '0104', '5103', '0116', '5019', '5150'}

Grott settings:

_Generic:
	version:             	 2.8.3
	verbose:             	 True
	trace:               	 False
	config file:         	 /config/grott/grott.ini
	minrecl:             	 100
	decrypt:             	 True
	compat:              	 False
	invtype:             	 min
	invtypemap:          	 {}
	include_all:         	 False
	blockcmd:            	 False
	noipf:               	 False
	time:                	 auto
	sendbuf:             	 True
	timezone:            	 local
	valueoffset:         	 6
	offset:              	 6
	inverterid:          	 automatic
	mode:                	 proxy
	grottip              	 default
	grottport            	 5279
_MQTT:
	nomqtt               	 True
	mqttip:              	 localhost
	mqttport:            	 1883
	mqtttopic:           	 energy/growatt
	mqttmtopic:          	 False
	mqttmtopicname:      	 energy/meter
	mqttinverterintopic: 	 False
	mqtttretain:         	 True
	mqtttauth:           	 True
	mqttuser:            	 mosquito
	mqttpsw:             	 **secret**
_Growatt server:
	growattip:           	 47.91.67.66
	growattport:         	 5279
_PVOutput:
	pvoutput:            	 False
	pvdisv1:             	 False
	pvtemp:              	 False
	pvurl:               	 https://pvoutput.org/service/r2/addstatus.jsp
	pvapikey:            	 yourapikey
	pvinverters:         	 1
	pvsystemid:          	 systemid1
_Influxdb:
	influx:             	 False
	influx2:            	 False
	database:           	 grottdb
	ip:                 	 localhost
	port:               	 8086
	user:               	 grott
	password:           	 **secret**
	organization:       	 grottorg
	bucket:             	 grottdb
	token:              	 **secret**
_Extension:
	extension:          	 True
	extname:            	 grottext.ha
	extvar:             	 {'ha_mqtt_host': 'core-mosquitto', 'ha_mqtt_port': '1883', 'ha_mqtt_user': 'addons', 'ha_mqtt_password': 'aingei7aijieCei4ierieng3OhkaiGh4EshaapooT4aihaeJee5choh0IeVeiyoh', 'ha_mqtt_retain': False}

Grott proxy mode started
	 **********************************************************************************
	 - Grott - libscrc not installed, no CRC checking only record validation on length!
	 **********************************************************************************
Hostname : ef7b0eff-grott-beta
IP :  172.30.33.13 , port :  5279 

- Grott automatic protocol detection
	 - Grott data record length 278
	 - layout   :  T060120
	 - Record layout used :  T060120
	 - Growatt data decrypted V2
	 - Grott Growatt data decrypted
	 - Growatt plain data:
		 00330006010e01205847443643473732464500000000000000000000000000000000000000004
		 a434d30444136303039000000000000000000000000000000000000000018061713173b00c800
		 00008e00000922000009040000092c0000000a000000580000000c000000f300004f0cfffffff
		 1000000000000000000000000fffff9f6fffff5c1fffff78800000068000003dcfffffff50000
		 4ff100000000ffffe73e0000031d000001f400000fb700000fc000000fda00001cbf00003fda0
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 0000000000000dc8d
	 - Growatt new layout processing
		 - decrypt       :  True
		 - offset        :  6
		 - record layout :  T060120

	 - Grott data record date/time processing started
	 - date-time:  2024-06-23T19:23:59
	 - Grott values retrieved:
		 -  datalogserial        :  XXXXXXXXXX
		 -  pvserial             :  YYYYYYYYYY
		 -  voltage_l1           :  233.8
		 -  voltage_l2           :  230.8
		 -  voltage_l3           :  234.8
		 -  Current_l1           :  1.0
		 -  Current_l2           :  8.8
		 -  Current_l3           :  1.2
		 -  act_power_l1         :  24.3
		 -  act_power_l2         :  2023.6
		 -  act_power_l3         :  -1.5
		 -  app_power_l1         :  0.0
		 -  app_power_l2         :  0.0
		 -  app_power_l3         :  0.0
		 -  react_power_l1       :  -154.6
		 -  react_power_l2       :  -262.3
		 -  react_power_l3       :  -216.8
		 -  powerfactor_l1       :  0.1
		 -  powerfactor_l2       :  1.0
		 -  powerfactor_l3       :  -0.0
		 -  pos_rev_act_power    :  2046.5
		 -  pos_act_power        :  2046.5
		 -  rev_act_power        :  2046.5
		 -  app_power            :  0.0
		 -  react_power          :  -633.8
		 -  powerfactor          :  0.8
		 -  frequency            :  50.0
		 -  L1-2_voltage         :  402.3
		 -  L2-3_voltage         :  403.2
		 -  L3-1_voltage         :  405.8
		 -  pos_act_energy       :  735.9
		 -  rev_act_energy       :  1634.6
	 - MQTT jsonmsg: 
			 {"device": "XXXXXXXXXX", "time": "2024-06-23T19:23:59", "buffered": "no",
			 "values": {"datalogserial": "XXXXXXXXXX", "pvserial": "YYYYYYYYYY",
			 "voltage_l1": 2338, "voltage_l2": 2308, "voltage_l3": 2348, "Current_l1":
			 10, "Current_l2": 88, "Current_l3": 12, "act_power_l1": 243, "act_power_l2":
			 20236, "act_power_l3": -15, "app_power_l1": 0, "app_power_l2": 0,
			 "app_power_l3": 0, "react_power_l1": -1546, "react_power_l2": -2623,
			 "react_power_l3": -2168, "powerfactor_l1": 104, "powerfactor_l2": 988,
			 "powerfactor_l3": -11, "pos_rev_act_power": 20465, "pos_act_power": 20465,
			 "rev_act_power": 20465, "app_power": 0, "react_power": -6338, "powerfactor":
			 797, "frequency": 500, "L1-2_voltage": 4023, "L2-3_voltage": 4032,
			 "L3-1_voltage": 4058, "pos_act_energy": 7359, "rev_act_energy": 16346}}
	 - No MQTT message sent, MQTT disabled
	 - Grott Send data to PVOutput disabled 
	 - Grott Send data to Influx disabled 
	 - Grott extension processing started :  grottext.ha
	Grott HA 0.11.0 - creating XXXXXXXXXX config in HA, 33 to push
	Pushing 34 configurations payload to HA
	Configurations pushed
	 - Grott extension processing ended :  0

	 - Growatt packet received:
		  <socket.socket fd=5, family=2, type=1, proto=0, laddr=('172.30.33.13', 5279), raddr=('192.168.2.29', 11909)>
	 - Data less then minimum record length, data not processed

('47.91.67.66', 5279)>
	 - Growatt original Data:
		 \x00\x6a\x00\x06\x02\x3d\x01\x38\x1f\x35\x2b\x41\x22\x33\x43\x75\x34\x2a\x77
		 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
		 \x25\x34\x2c\x44\x30\x06\x44\x5f\x47\x58\x74\x74\x47\x72\x6f\x77\x61\x74\x74
		 \x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x79\x72\x63\x54\x65\x54\x71\x72
		 \xac\x67\xb8\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f
		 \x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
		 \x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74
		 \x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77
		 \x61\x74\x74\x47\x72\x6f\x77\x75\x74\x60\x60\x72\x6f\x77\x61\x74\x74\x47\x72
		 \x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74
		 \x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61
		 \x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f
		 \x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x75\x5c\x60\x08
		 \x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74
		 \x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77
		 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
		 \x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74
		 \x47\x72\x6f\x77\x75\x24\x60\x30\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61
		 \x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f
		 \x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
		 \x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74
		 \x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x75\x0c\x60\xd8\x72\x6f\x77
		 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
		 \x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74
		 \x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61
		 \x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f
		 \x77\x75\xd4\x60\x80\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47
		 \x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74
		 \x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77
		 \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
		 \x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x19\xd1
	 - Grott automatic protocol detection
	 - Grott data record length 581
	 - layout   :  T060138XMIN
	 - no matching record layout found, try generic
	 - Record layout used :  T060138XMIN
	 - Growatt data decrypted V2
	 - Grott Growatt data decrypted
	 - Growatt plain data:
		 006a0006023d01385847443643473732464500000000000000000000000000000000000000004
		 a434d30444136303039000000000000000000000000000000000000000018061713173b0613d8
		 13ff0000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000001400142700000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 0000000000000000000000001428144f000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000145014770000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000001478149f00000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000014a014c7000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00000000000000000000000000000000000000000000000000000000000000000000000000000
		 00078a5
	 - Grott data ack record or data record not defined no processing done

	 - Growatt packet received:
		  <socket.socket fd=5, family=2, type=1, proto=0, laddr=('172.30.33.13', 5279), raddr=('192.168.2.29', 11909)>
	 - Data less then minimum record length, data not processed

**Comment by ZonPV** [comment]
You better try in your config

nomqtt = False

As in your log there is the sentence MQTT is disabled.

**Comment by InvertedMinor** [comment]
already done in my grott.ini

`[MQTT]
# Mqtt parameters definitions
# Be aware nomqtt = True means no MQTT processing will be done!!!!!!

nomqtt = False
ip = localhost
port = 1883
topic= energy/growatt
auth = True
user = mosquito
password = QQQQQ
retain = True`

So why is it then switching to True?

**Comment by InvertedMinor** [comment]
Issue resolved. Inverter now 100% visible in HA. Confusion on my side with all the variants and options of the Grott server & HA.
