### ISSUE TITLE
Sharing some info: Growatt ShineLanBox needed a reboot

### ISSUE THREAD

**Issue by redthor** [johanmeijer/grott#58]
Just thought I'd share that I was not getting any data with the ShineLanBox even though the settings had changed. I had to unplug it and plug it back in, then it started to send Grott data.

Settings:
![Shinelink-Network-Settings-ge](https://user-images.githubusercontent.com/767896/124371521-ccf1d180-dcc5-11eb-8a67-b0d5799c8fd2.png)

ShineLanBox:
![growatt-shine-lan-box](https://user-images.githubusercontent.com/767896/124371538-01fe2400-dcc6-11eb-9969-3e1f03b61443.jpg)

**Comment by spathix** [comment]
Thanks for sharing this! Just wondering if there was anything else you had to do to get this working? Any chance you can share your config? (minus sensitive information of course).

I have 2 of these boxes as I have 2 inverters, and I cannot get either of them to work correctly (with or without grott as a proxy). The RF dongles attach fine but there is no network connectivity on the cloud led.
