### ISSUE TITLE
Growatt SPF 3000

### ISSUE THREAD

**Issue by macfloripa** [johanmeijer/grott#67]
Hello,
First of all, thanks for your efforts with this project. I have just purchased and installed a SPF 3000 model and need some assistance.

I'm running the 2.6.1 version, as per your instructions. Standalone, proxy (not docker) on a raspberry pi, together with influx.

I've specified inverter=spf  in the ini file, and am getting some good and bad values from the program.

----

EDIT

I just realized that I Do have an SPF, not SPH Model, so the data I posted here before does not apply to my problem.

I am having problems with a few of the fields using the spf record layout.

Specifically, the epvtoday is always Zero.

There are probably more fields that are not correct, but I've just noticed this one.

I've attached my grott messages and an excel from the server.growatt.com site.

[grott.output.txt](https://github.com/johanmeijer/grott/files/7072954/grott.output.txt)
[DBG0A4103M storage data - 2021-08-29_2021-08-29.xls](https://github.com/johanmeijer/grott/files/7072955/DBG0A4103M.storage.data.-.2021-08-29_2021-08-29.xls)

Any suggestions?

Thanks

**Comment by macfloripa** [comment]
ok. Some additional information. I upgraded my shinewifi firmware version from 1.7.66 to 3.0.0.2 and now grott is not able to read the data from the unit. Seems like a new format?

Aug 31 11:32:37 zm grott[28397]:          - Growatt original Data:
Aug 31 11:32:37 zm grott[28397]:                  \x00\x02\x00\x06\x01\x5f\x01\x50\x0a\x25\x28\x47\x20\x40\x44\x77\x38\x5f\x77
Aug 31 11:32:37 zm grott[28397]:                  \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
Aug 31 11:32:37 zm grott[28397]:                  \x2b\x35\x26\x44\x35\x73\x43\x5f\x44\x2c\x74\x74\x47\x72\x6f\x77\x61\x74\x74
Aug 31 11:32:37 zm grott[28397]:                  \x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x74\x7c\x6b\x4c\x68\x46\x74\x61
Aug 31 11:32:37 zm grott[28397]:                  \x74\x74\x6b\x72\x6a\x74\x82\x74\x74\x47\x72\x66\xe5\x61\x74\x74\x47\x72\x5f
Aug 31 11:32:37 zm grott[28397]:                  \x77\x61\x74\x74\x4b\x48\x6f\x77\x6d\x02\x74\x47\x72\x6f\x77\x61\x74\x74\x54
Aug 31 11:32:37 zm grott[28397]:                  \xaf\x6f\x13\x6e\x2c\x7c\x18\x65\x1b\x7f\xf9\x63\x00\x47\x72\x6e\x5b\x61\x8a
Aug 31 11:32:37 zm grott[28397]:                  \x74\x2d\x72\x6f\x77\x61\x74\x74\x47\x72\x6e\x0c\x61\x74\x74\x49\x72\x61\x77
Aug 31 11:32:37 zm grott[28397]:                  \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x3a\xf3\x47\x5f
Aug 31 11:32:37 zm grott[28397]:                  \x6f\x2e\x61\x75\x74\x47\x72\x6f\x77\x61\x74\x71\x47\x72\x6f\x09\x61\x74\x74
Aug 31 11:32:37 zm grott[28397]:                  \x47\x72\x6f\x77\x61\x74\x74\x47\x71\x6f\x77\x61\x3c\x74\x47\x72\x66\x77\x61
Aug 31 11:32:37 zm grott[28397]:                  \x74\x0f\x47\x72\x6f\x71\x61\x74\x74\x3e\x72\x6f\x77\x61\x74\x74\x47\x72\x6f
Aug 31 11:32:37 zm grott[28397]:                  \x77\x61\x74\x78\x97\x72\x6f\x7c\x8b\x74\x74\x45\x8a\x6f\x77\x61\x74\x74\x47
Aug 31 11:32:37 zm grott[28397]:                  \x72\x6f\x77\x50\x74\x33\x47\x72\x6f\x79\x61\x74\x74\xad\x72\x6f\x77\x3b\x74
Aug 31 11:32:37 zm grott[28397]:                  \xf2\x47\x5f\x6f\x76\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77
Aug 31 11:32:37 zm grott[28397]:                  \x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72
Aug 31 11:32:37 zm grott[28397]:                  \x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74
Aug 31 11:32:37 zm grott[28397]:                  \x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61\x74\x74\x47\x72\x6f\x77\x61
Aug 31 11:32:37 zm grott[28397]:                  \x74\x74\x46\x72\x6e\x77\x60\x74\x74\x47\x72\x6f\x77\x61\x74\x66\x98
Aug 31 11:32:37 zm grott[28397]:          - Grott automatic protocol detection
Aug 31 11:32:37 zm grott[28397]:          - Grott data record length 359
Aug 31 11:32:37 zm grott[28397]:          - layout   :  T060150SPF
Aug 31 11:32:37 zm grott[28397]:          - no matching record layout found, try generic
Aug 31 11:32:37 zm grott[28397]:          - no matching record layout found, standard processing performed
Aug 31 11:32:37 zm grott[28397]:          - Record layout used :  none
Aug 31 11:32:37 zm grott[28397]:          - Growatt data decrypted V2
Aug 31 11:32:37 zm grott[28397]:          - Grott Growatt data decrypted
Aug 31 11:32:37 zm grott[28397]:          - Growatt plain data:
Aug 31 11:32:37 zm grott[28397]:                  00020006015f01504d574730413430304a3000000000000000000000000000000000000000004
Aug 31 11:32:37 zm grott[28397]:                  442473041343130334d000000000000000000000000000000000000000015081f0b1a29030000
Aug 31 11:32:37 zm grott[28397]:                  002c000503e3000000000992000000000030000000000c3a00000c76000000000000000013dd0
Aug 31 11:32:37 zm grott[28397]:                  0640f58085f1774089817740000012c00fe006a0000000000000000017b0000000e000e000000
Aug 31 11:32:37 zm grott[28397]:                  000000000000000000000000004e87002d0059000100000000000000050000007e00000000000
Aug 31 11:32:37 zm grott[28397]:                  000000000000300000048000000090000007b0000000600000079000000000000000000000000
Aug 31 11:32:37 zm grott[28397]:                  0cd000000bea000002f80000000000000000003100470000000e000000ea0000005a0086002d0
Aug 31 11:32:37 zm grott[28397]:                  00100000000000000000000000000000000000000000000000000000000000000000000000000
Aug 31 11:32:37 zm grott[28397]:                  00000000000000000000000000000000000000000000000000000000000000000000000001000
Aug 31 11:32:37 zm grott[28397]:                  10001000000000000000012df
Aug 31 11:32:37 zm grott[28397]:          - Grott data ack record or data record not defined no processing done

**Comment by johanmeijer** [comment]
T060150SPF is a standard buffered record. Should not give a problem but I see thee is a bug in the coding for this record. 
I Will repair it. 

Do you run Grott natively or in a docker container?

**Comment by macfloripa** [comment]
Hi Johan,
I run it Native on a raspberry pi.
Thanks.

**Comment by johanmeijer** [comment]
@macfloripa, I have made a change to 2.6 branch (2.6.1a). Hopefully it works now!

**Comment by macfloripa** [comment]
Nice. I'm getting data again, and at a first quick glance, it looks good. I'll keep an eye on it for a time and see if I notice any issues. Thanks so much!

**Comment by macfloripa** [comment]
All seems good. Question, does your docker image contain the changes you made? I want to move to a docker installation on my NAS (QNap). Thanks

**Comment by johanmeijer** [comment]
No I have not created a  new  docker image yet. Will do it the comming days,

**Comment by gabrielpc1190** [comment]
I can confirm for SPF 3000 TL-LVM 24 volts the image ledidobe/grott:2.6.1c works really good!

**Comment by gabrielpc1190** [comment]
I have the examples for Home Assistant already.
[mqtt-for-jbd-and-grott.zip](https://github.com/johanmeijer/grott/files/7518184/mqtt-for-jbd-and-grott.zip)
It's a file that contains a yaml file I included on my configuration file.
