### ISSUE TITLE
Json markup error pv2watt:

### ISSUE THREAD

**Issue by Jeltel** [johanmeijer/grott#7]
json i got is in version 1.0.8
```
{
    "device": "xxxxxxxxxx",
    "time": "2020-04-04T12:38:06",
    "values": {
        "pvstatus": 1,
        "pv1watt": 6,
        "pv2watt:": 18056,
        "pvpowerout": 17493,
        "pvfrequentie": 5000,
        "pvgridvoltage": 2458,
        "pvenergytoday": 74,
        "pvenergytotal": 1601
    }
}
``` 
But pv2watt has another : in it: `"pv2watt:": 18056,` should be `"pv2watt": 18056,`

Just a bit confusing :)

**Comment by johanmeijer** [comment]
Yes! This an error I will change that ( I don not have 2 strings and use only PV1).

Thanks.

**Comment by Jeltel** [comment]
Found it in rule 322 of grott.py, changed it myself.
Don't know how to do a pull request though.

**Comment by johanmeijer** [comment]
I will change it! Version 1.0.9 is on his way.

**Comment by Jeltel** [comment]
The ':' is gone in version 1.0.9. Thanks :)
