### ISSUE TITLE
Linux service file has incorrect link to files

### ISSUE THREAD

**Issue by Deshmir** [johanmeijer/grott#71]
When installing grott as a service, the service file links to /home/pi/growatt.
However, when you git clone the repo, it downloads itself to "grott".

Easy fix: change the installation manual to  ```git clone [url] growatt```
Longer fix: change the service file (grott.service) on line 13 and line 14 to the follwing:
```
13 WorkingDirectory=/home/pi/grott/
14 ExecStart=-/usr/bin/python3 -u /home/pi/grott/grott.py -v
```

**Comment by johanmeijer** [comment]
I think this one can be closed?
